"""Branch 2 of the separation induction (O18, section 82).

Assume Phi_D in W_type.  The relative nullity theorem gives, for a map g
realising the homotopy inverse, either
  (Branch 1) g null  ->  el(W) contractible  ->  contradiction with W1, or
  (Branch 2) g factors through a carrier stratum quotient
             W' = l/N_l, whence  id_W  ~  j . rho  in Ho(type).

In Branch 2, if the carrier also admits a STRICT retraction
rho_0 with rho_0 . j = id (a twisted end class restricting to a deck
element on l), then j is a split mono AND a split epi in Ho(type), hence
an ISOMORPHISM there, i.e. j in W_type.  Since W_type is contained in
W_test (the basic inclusion of the programme), j is then automatically a
test equivalence -- no computation needed -- and

     Phi'' := j . Phi_{Q_l} : J_{Q_l}/Q_l -> W

is a test equivalence (composite) which is NOT a type equivalence
(2-out-of-3 with j in W_type would force Phi_{Q_l} in W_type, against the
inductive hypothesis SEP(Q_l)).  So W has a witness either way.

Moreover in Branch 2, el(W) ~ el(W') forces pi_1(el W') = 1, i.e. Q_l is
REFLECTION-GENERATED, and the kills K1/K2 exclude Q_l fixed or free, so
Q_l is reflection-generated mixed of dimension m < n: the induction
hypothesis applies.

This script verifies, for every reflection-generated mixed class of B_4
and every carrier stratum, that the Branch-2 hypotheses hold:
    (a) a strict retraction exists, and
    (b) Q_l is reflection-generated and mixed.
"""
import sys, itertools
from collections import deque
sys.path.insert(0, 'scripts')
from strata_retract import build

n = 4
ELEMS, idx, ID, NE, MUL, INV, ACT = build(n)
NV = 1 << n
REFL = []
for a in range(NE):
    p, s = ELEMS[a]
    seen = [False]*n; ok = a != ID
    for i in range(n):
        if seen[i]: continue
        sg = s[i]; j = p[i]; seen[i] = True
        while j != i:
            seen[j] = True; sg ^= s[j]; j = p[j]
        if sg & 1: ok = False
    REFL.append(ok)
def close(g):
    S = {ID}; dq = deque([ID])
    while dq:
        x = dq.popleft()
        for a in g:
            y = MUL[x][a]
            if y not in S: S.add(y); dq.append(y)
    return frozenset(S)
subs = {frozenset([ID]): []}
frontier = list(subs.items())
while frontier:
    new = []
    for H, gens in frontier:
        for g in range(NE):
            if g in H: continue
            H2 = close(gens + [g])
            if H2 not in subs:
                subs[H2] = gens + [g]; new.append((H2, gens + [g]))
    frontier = new
classes = {}
for H in subs:
    key = min(tuple(sorted(MUL[MUL[g][a]][INV[g]] for a in H))
              for g in range(NE))
    classes.setdefault(key, H)
tgt = []
for H in classes.values():
    R = [a for a in H if REFL[a]]
    if not R: continue
    if any(all(ACT[a][v] == v for a in R) for v in range(NV)): continue
    if close(R) != H: continue
    tgt.append(sorted(H))
print(f"n=4: reflection-generated mixed classes {len(tgt)}", flush=True)

def qdata(Ls, Nl):
    """type of Q_l acting on l, and whether Q_l is reflection-generated"""
    Pl = [a for a in Nl if all(ACT[a][w] == w for w in Ls)]
    Rq = [a for a in Nl if a not in Pl and any(ACT[a][w] == w for w in Ls)]
    fixed = any(all(ACT[a][w] == w for a in Nl) for w in Ls)
    if fixed: return "fixed", False
    if not Rq: return "free", False
    # <R(Q)> = image of the subgroup generated by Rq together with P_l
    gen = close(Rq + Pl)
    refgen = (set(gen) == set(Nl))
    commonR = any(all(ACT[a][w] == w for a in Rq) for w in Ls)
    return ("mixed" if not commonR else "mixed(degenerate)"), refgen

ok_all = 0
for H in sorted(tgt, key=len):
    loci = {}
    for a in H:
        if REFL[a]:
            L = frozenset(v for v in range(NV) if ACT[a][v] == v)
            loci[L] = 1
    maximal = [sorted(L) for L in loci if not any(L < L2 for L2 in loci)]
    gg = None
    for i, a in enumerate(H):
        for b in H[i:]:
            if len(close([a, b])) == len(H): gg = [a, b]; break
        if gg: break
    if gg is None:
        gg = []; span = {ID}
        for a in H:
            if a in span: continue
            gg.append(a); span = set(close(gg))
            if len(span) == len(H): break
    word = {ID: []}; dq = deque([ID])
    while dq:
        x = dq.popleft()
        for k, g in enumerate(gg):
            y = MUL[x][g]
            if y not in word: word[y] = word[x] + [k]; dq.append(y)
    orbs = []; seenv = [False]*NV
    for v in range(NV):
        if seenv[v]: continue
        orb = {ACT[a][v] for a in H}
        for w in orb: seenv[w] = True
        orbs.append(sorted(orb))
    seen = set(); rows = []
    for Ls in maximal:
        key = min(tuple(sorted(ACT[g][v] for v in Ls)) for g in H)
        if key in seen: continue
        seen.add(key)
        Nl = [a for a in H if {ACT[a][v] for v in Ls} == set(Ls)]
        # twisted end classes and strict retractions on this stratum
        twisted = False; strict = False
        for imgs in itertools.product(Nl, repeat=len(gg)):
            d = {}
            for x in H:
                y = ID
                for k in word[x]: y = MUL[y][imgs[k]]
                d[x] = y
            if not all(d[MUL[a][b]] == MUL[d[a]][d[b]]
                       for a in H for b in H): continue
            ch = []
            for orb in orbs:
                v = orb[0]; St = [a for a in H if ACT[a][v] == v]
                ws = [w for w in Ls if all(ACT[d[a]][w] == w for a in St)]
                ch.append((orb, ws))
            if any(not ws for _, ws in ch): continue
            if any(any(not all(ACT[d[x]][w] == w for x in H) for w in ws)
                   for _, ws in ch): twisted = True
            if not strict:
                for k in Nl:
                    good = True
                    for orb, ws in ch:
                        v = orb[0]
                        if v in Ls:
                            if ACT[k][v] not in ws: good = False; break
                    if good: strict = True; break
        if twisted:
            t, refgen = qdata(Ls, Nl)
            rows.append((len(Ls), len(Nl), t, refgen, strict))
    if not rows:
        print(f"   |D|={len(H):3d}: no carrier (absolute nullity)", flush=True)
        ok_all += 1
        continue
    # CORRECT criterion: Branch 2 can only occur at a carrier where
    # el(W) ~ el(W'), which forces pi_1(el W') = 1, i.e. Q_l
    # reflection-generated (and K1/K2 exclude fixed/free).  So a carrier
    # is handled if either Q_l is NOT reflection-generated (Branch 2
    # impossible there) or Q_l is reflection-generated mixed and a strict
    # retraction exists (induction on the dimension applies).
    good = all((not refgen) or (t == "mixed" and strict)
               for _, _, t, refgen, strict in rows)
    ok_all += good
    print(f"   |D|={len(H):3d}: carriers " + "; ".join(
        f"|l|={a} |N|={b} Q={t}{'/refl-gen' if r else '/NOT refl-gen'}"
        f" strict-retract={'yes' if s else 'NO'}"
        for a, b, t, r, s in rows) +
        f"  -> {'HANDLED' if good else '*** GAP ***'}", flush=True)
print(f"   classes where every carrier is handled: {ok_all}/{len(tgt)}", flush=True)
