"""(T-C) part 12: quotient-essential invariant classes for G2 = B2 (order 8).

The median collage Phi = (F(d,a,t), F(d,~a,t)) is equivariant for the FULL
signed-permutation group B2 = D4 = <sw, r> of the square, with the twisted
join action generated by

    sw~ : (d,a,t) |-> (d,~a,t)
    nb~ : (d,a,t) |-> (~d,~a,t)          ( = r~^2 )
    r~  : (d,a,t) |-> (a,~d,~t)

(dihedral relations hold on the nose; verified in-line below).  Hence Phi
descends to  Phi_G2 : J/G2 -> square/G2.

Census (analogue of part 11 for K): a G2-invariant interior class [c] of
J/G2([2]) factors through the contractible cover J iff some representative
c' in its 8-element G2_J-orbit is strictly invariant: SW(c')=c', NB(c')=c',
R(c')=c' component-wise.  Essential = no such representative.  Also counts
the crossing-boundary classes.  Everything exact and finite (168^3 loop).
"""
import sys
sys.path.insert(0, 'scripts')
from collage_type_lib import build, monotone_masks, NOT, gen

N, leq, rho = build(2)
dm = monotone_masks(N, leq)
notf = {m: NOT(m, N, rho) for m in dm}
X, Y = gen(0,2,N), gen(1,2,N)
FULL = (1<<N)-1

def swp(p):
    vx,vnx,vy,vny = p&1,(p>>1)&1,(p>>2)&1,(p>>3)&1
    return vy|(vny<<1)|(vx<<2)|(vnx<<3)
def SW(m):
    r=0
    for p in range(N):
        if (m>>swp(p))&1: r|=1<<p
    return r
def lswap(p):
    vx,vnx,vy,vny = p&1,(p>>1)&1,(p>>2)&1,(p>>3)&1
    return vnx|(vx<<1)|(vny<<2)|(vy<<3)
def NB(m):
    r=0
    for p in range(N):
        if (m>>lswap(p))&1: r|=1<<p
    return r
def rotp(p):
    # substitution x := ~y, y := x  (rotation r of the square)
    vx,vnx,vy,vny = p&1,(p>>1)&1,(p>>2)&1,(p>>3)&1
    return vny|(vy<<1)|(vx<<2)|(vnx<<3)
def R(m):
    r=0
    for p in range(N):
        if (m>>rotp(p))&1: r|=1<<p
    return r

# sanity: R has order 4, R^2 = NB, dihedral relation SW R SW = R^3 on masks
assert R(R(X)) == NB(X) and R(R(Y)) == NB(Y)
assert R(R(R(R(X)))) == X
assert SW(R(SW(X))) == R(R(R(X))) and SW(R(SW(Y))) == R(R(R(Y)))
# rotation acts correctly on generators: R(x)=~y, R(y)=x
assert R(X) == notf[Y] and R(Y) == X

def face(m, var, e):
    r=0
    for p in range(N):
        if var==0: q=(p&~0b11)|(0b10 if e==0 else 0b01)
        else: q=(p&~0b1100)|(0b1000 if e==0 else 0b0100)
        if (m>>q)&1: r|=1<<p
    return r
def to1(m2, var, e):
    f2 = face(m2, var, e); r=0
    for vy in (0,1):
        for vny in (0,1):
            if var==0: p = 0b10 | (vy<<2) | (vny<<3)
            else: p = (vy) | (vny<<1) | 0b1000
            if (f2>>p)&1: r |= 1 << (vy | (vny<<1))
    return r

N1, leq1, rho1 = build(1)
not1 = {m: NOT(m,N1,rho1) for m in monotone_masks(N1,leq1)}
X1 = gen(0,1,N1); FULL1=(1<<N1)-1
def norm1(c):
    # end classes of J/G2: r~ glues the D-end to the A-end via phi |-> ~phi,
    # so both ends normalize to a single label 'E'
    d,a,t = c
    if t==0: return ('E', min(d,not1[d]))
    if t==FULL1: return ('E', min(a,not1[a]))
    return ('C', min([(d,a,t),(d,not1[a],t),(not1[d],not1[a],t),(not1[d],a,t),
                      (a,not1[d],not1[t]),(a,d,not1[t]),
                      (not1[a],d,not1[t]),(not1[a],not1[d],not1[t])]))
L = norm1((0,0,X1)); LR = norm1((0,0,not1[X1]))

def orbit8(c):
    d,a,t = c
    k = [(d,a,t),(d,notf[a],t),(notf[d],notf[a],t),(notf[d],a,t)]
    rr = (a, notf[d], notf[t])
    d2,a2,t2 = rr
    k += [(d2,a2,t2),(d2,notf[a2],t2),(notf[d2],notf[a2],t2),(notf[d2],a2,t2)]
    return k

def norm2(c):
    d,a,t = c
    if t==0 or t==FULL: raise ValueError
    return ('C', min(orbit8(c)))

seen = {}
for d in dm:
    for a in dm:
        for t in dm:
            if t == 0 or t == FULL: continue
            c = (d,a,t); n0 = norm2(c)
            if n0 in seen: continue
            if norm2((SW(d),SW(a),SW(t))) != n0: continue
            if norm2((NB(d),NB(a),NB(t))) != n0: continue
            if norm2((R(d),R(a),R(t))) != n0: continue
            strict = any(SW(dd)==dd and SW(aa)==aa and SW(tt)==tt and
                         NB(dd)==dd and NB(aa)==aa and NB(tt)==tt and
                         R(dd)==dd and R(aa)==aa and R(tt)==tt
                         for (dd,aa,tt) in orbit8(c))
            faces = [norm1((to1(d,v,e), to1(a,v,e), to1(t,v,e)))
                     for v in (0,1) for e in (0,1)]
            good_bdy = faces == [L,LR,L,LR]
            seen[n0] = (strict, good_bdy, c)

ess = [(k,v) for k,v in seen.items() if not v[0]]
essb = [(k,v) for k,v in ess if v[1]]
strb = [(k,v) for k,v in seen.items() if v[0] and v[1]]
print(f"G2 interior invariant classes: {len(seen)}; essential: {len(ess)}; "
      f"essential with l-boundary: {len(essb)}; factoring with l-boundary: {len(strb)}")
for k,v in ess[:10]:
    print("  essential:", v[2], "boundary-crossing:", v[1])
