"""Cubical (type-side) homology of W = the monotone dunce hat
(O22).  Normalized cubical chains: C_k = Z[W(k)-classes] modulo
the subgroup generated by DEGENERATE classes (cells factoring
through a non-invertible site surjection [k] ->> [j], j < k --
equivalently: cells whose class contains a cell of the form
d o s with s a proper "degeneracy" = a tuple of F(k)-elements
spanning a proper subalgebra... practical criterion: the cell,
as a pair of monotone functions, depends on at most... we use:
a level-k cell D is degenerate iff D = E o s for some cell E at
level k-1 and site map s: [k] -> [k-1] (s = (k-1)-tuple over
F(k)); machine: mark classes hit by precomposition images of
level-(k-1) cells along all such s).
Boundary: cubical d = sum_i (-1)^i (d_i^1 - d_i^0).
Compute H_1, H_2 over Z (Smith) and over F_2.
"""
import sys, itertools
sys.path.insert(0, 'scripts')
from cand05_independent import FF, pre, congruence
from dedekind_zhomology import smith_diag

CL = congruence(3)
def cls(k, c): return CL[k][c]
reps = {k: sorted(set(CL[k].values())) for k in range(4)}
ind = {k: {c: i for i, c in enumerate(reps[k])} for k in range(4)}
print("class counts:", [len(reps[k]) for k in range(4)], flush=True)

# degenerate classes at level k: images of level k-1 cells along
# all site maps s: [k] -> [k-1] (i.e. (k-1)-tuples over F(k))
def degenerate_set(k):
    _, fk = FF(k)
    degs = set()
    for E in reps[k - 1]:
        for s in itertools.product(fk, repeat=k-1):
            degs.add(cls(k, pre(E, s, k-1, k)))
    return degs

DEG = {k: degenerate_set(k) for k in (1, 2, 3)}
print("degenerate:", {k: len(DEG[k]) for k in DEG}, flush=True)

# faces d_i^eps: site maps [k-1] -> [k]: insert const eps at pos i
def face(i, eps, k):
    _, fk1 = FF(k - 1)
    pts1 = FF(k - 1)[0]
    def var(j): return tuple(p[j] for p in pts1)
    out = []
    vi = 0
    for a in range(k):
        if a == i: out.append(tuple(eps for _ in pts1))
        else: out.append(var(vi)); vi += 1
    return tuple(out)

def boundary_matrix(k):
    """d: C_k -> C_{k-1} on nondegenerate basis"""
    basis_k = [c for c in reps[k] if c not in DEG.get(k, set())]
    basis_k1 = [c for c in reps[k-1]
                if c not in DEG.get(k-1, set())]
    bi = {c: i for i, c in enumerate(basis_k1)}
    M = [[0]*len(basis_k) for _ in range(len(basis_k1))]
    for j, c in enumerate(basis_k):
        for i in range(k):
            for eps in (0, 1):
                f = cls(k-1, pre(c, face(i, eps, k), k, k-1))
                if f in bi:
                    M[bi[f]][j] += (-1)**i * (1 if eps == 1 else -1)
    return M, len(basis_k), len(basis_k1)

d1, n1, n0 = boundary_matrix(1)
d2, n2, _ = boundary_matrix(2)
d3, n3, _ = boundary_matrix(3)
print("nondegenerate counts:", n0, n1, n2, n3, flush=True)
s1 = smith_diag(d1); s2 = smith_diag(d2); s3 = smith_diag(d3)
r1 = sum(1 for x in s1 if x); r2 = sum(1 for x in s2 if x)
r3 = sum(1 for x in s3 if x)
b0 = n0 - r1; b1 = n1 - r1 - r2; b2 = n2 - r2 - r3
t1 = [x for x in s2 if x not in (0,1)]
t2 = [x for x in s3 if x not in (0,1)]
print(f"cubical H_0: rank {b0}")
print(f"cubical H_1: rank {b1}, torsion {t1}")
print(f"cubical H_2: rank {b2}, torsion {t2}")
