"""O26: the five-chain atom T = <(u&v&w, u&v, u&(v|w))> is an
irreducible three-dimensional shape: its kernel congruence is
NOT generated by its restriction to levels <= 2.

Data: T has 9 cell classes at level 1 (of 27), 36 at level 2
(of 216), 400 at level 3 (of 8000); the congruence generated by
all level-<=2 kernel pairs has 4288 classes at level 3, far
coarser than the true 400.  Hence no assembly from graph and
two-dimensional data can present T: the regularity of the
4-chain-image atoms is a genuinely three-dimensional question,
addressed via the coasphericity criterion.
"""
import sys, itertools
sys.path.insert(0, 'scripts')
from dedekind_site import F, compose

def proj(k, i):
    pts, _ = F(k)
    return tuple(p[i] for p in pts)
def meet(*xs):
    out = xs[0]
    for x in xs[1:]: out = tuple(p & q for p, q in zip(out, x))
    return out
def join(*xs):
    out = xs[0]
    for x in xs[1:]: out = tuple(p | q for p, q in zip(out, x))
    return out

u, v, w = proj(3,0), proj(3,1), proj(3,2)
z = (meet(u,v,w), meet(u,v), meet(u, join(v,w)))

def zc(sigma, k):
    return tuple(compose(comp, sigma, 3, k) for comp in z)

_, F1 = F(1); _, F2 = F(2); _, F3 = F(3)
def kernel_pairs(k, Fk):
    cells = list(itertools.product(Fk, repeat=3))
    byval = {}
    for s in cells:
        byval.setdefault(zc(s, k), []).append(s)
    pairs = []
    for vlist in byval.values():
        for i in range(len(vlist)):
            for j in range(i+1, len(vlist)):
                pairs.append((vlist[i], vlist[j]))
    return len(cells), len(byval), pairs

n1, c1, P1 = kernel_pairs(1, F1)
n2, c2, P2 = kernel_pairs(2, F2)
print(f"level 1: {n1} cells -> {c1} classes")
print(f"level 2: {n2} cells -> {c2} classes")

parent = {}
cells3 = list(itertools.product(F3, repeat=3))
for s in cells3: parent[s] = s
def find(x):
    while parent[x] != x:
        parent[x] = parent[parent[x]]; x = parent[x]
    return x
def union(a, b):
    ra, rb = find(a), find(b)
    if ra != rb: parent[ra] = rb
maps_to = {1: list(itertools.product(F3, repeat=1)),
           2: list(itertools.product(F3, repeat=2))}
for (j, pairs) in ((1, P1), (2, P2)):
    for (A, B) in pairs:
        for m in maps_to[j]:
            union(tuple(compose(c, m, j, 3) for c in A),
                  tuple(compose(c, m, j, 3) for c in B))
gen = len({find(s) for s in cells3})
true = len({zc(s, 3) for s in cells3})
print(f"level 3: generated {gen} classes vs true kernel {true}")
print("=> kernel NOT generated in level <= 2:", gen != true)
