"""O28 stage 3a: shape-by-shape chain approximation -- calibration
sweep over subobjects of cubes.

For a subpresheaf S of a cube, chain approximation Ch(S) into S
requires (necessary condition, via (A) + Real left Quillen) that
the SORTED subcomplex of the triangulation T(S) has the same
F2-homology as T(S) itself (the validated test invariant,
dedekind_triangulate.py conventions).  Sweep:
  - all cyclic atoms <z> of cube^2 (z of level <= 2, deduped),
  - the standard shapes: boundary, horns, realized dDelta/Lambda,
    diagonal edge, unions of two atoms (sample),
  - frontier atoms of cube^3: the five-chain atom and all <z>
    with a 4-chain in the image poset (sampled),
and report every shape where sorted-Betti != T-Betti.
"""
import sys, itertools
sys.path.insert(0, 'scripts')
from dedekind_site import F, compose
from dedekind_triangulate import rank2, coface as wall_coface

def coface_T(i, q):
    f = tuple(x if x < i else x + 1 for x in range(q))
    idx = []
    for ii in range(1, q + 1):
        ks = [kk for kk in range(q) if f[kk] >= ii]
        idx.append(min(ks) if ks else q)
    return tuple(o_stat_t(kk, q - 1) for kk in idx)

def o_stat_t(j, m):
    pts, _ = F(m)
    if j <= 0: return tuple(1 for _ in pts)
    if j > m: return tuple(0 for _ in pts)
    return tuple(1 if sum(p) >= j else 0 for p in pts)
def sort_sub(q): return tuple(o_stat_t(j, q) for j in range(1, q+1))
def rest(cell, u, j, k):
    return tuple(compose(c, u, j, k) for c in cell)

K = 3
def atom(z, j, n):
    """subpresheaf generated by cell z (n-tuple over F(j))"""
    S = {}
    for k in range(K + 1):
        _, Dk = F(k)
        S[k] = {rest(z, u, j, k) for u in itertools.product(Dk, repeat=j)}
    return S
def union(*Ss):
    return {k: set().union(*(S[k] for S in Ss)) for k in range(K + 1)}

def betti(S, sorted_only):
    lv = {}
    for k in range(K + 1):
        cells = sorted(S[k])
        if sorted_only:
            cells = [c for c in cells
                     if rest(c, sort_sub(k), k, k) == c]
        lv[k] = cells
    ind = {k: {c: i for i, c in enumerate(lv[k])} for k in lv}
    cof = coface_T if sorted_only else wall_coface
    r = {}
    for q in range(1, K + 1):
        cols = []
        for cell in lv[q]:
            v = 0
            for i in range(q + 1):
                fc = rest(cell, cof(i, q), q, q - 1)
                v ^= 1 << ind[q - 1][fc]
            cols.append(v)
        r[q] = rank2(cols)
    b = [len(lv[0]) - r[1]]
    for q in range(1, K):
        b.append(len(lv[q]) - r[q] - r[q + 1])
    return b

# ---- cube^2 shapes ----
shapes = []
_, D2 = F(2)
seen = set()
for z in itertools.product(D2, repeat=2):
    S = atom(z, 2, 2)
    key = frozenset(S[2])
    if key in seen: continue
    seen.add(key)
    shapes.append((f"atom2:{len(S[2])}c", S))
print(f"cube^2 atoms (distinct): {len(shapes)}", flush=True)

xv = tuple(p[0] for p in F(1)[0]); c0 = tuple(0 for _ in F(1)[0])
c1 = tuple(1 for _ in F(1)[0])
edges = {'x1=0': (c0, xv), 'x1=1': (c1, xv),
         'x2=0': (xv, c0), 'x2=1': (xv, c1), 'diag': (xv, xv)}
E = {n: atom(z, 1, 2) for n, z in edges.items()}
shapes.append(("bdry", union(E['x1=0'],E['x1=1'],E['x2=0'],E['x2=1'])))
for omit in ('x1=0','x1=1','x2=0','x2=1'):
    shapes.append((f"horn-no-{omit}",
                   union(*(E[g] for g in edges if g not in (omit,'diag')))))
shapes.append(("dDelta2", union(E['x1=1'], E['diag'], E['x2=0'])))
shapes.append(("Lambda2-noD", union(E['x1=1'], E['x2=0'])))
shapes.append(("Lambda2-noA", union(E['diag'], E['x2=0'])))
shapes.append(("Lambda2-noB", union(E['x1=1'], E['diag'])))

# unions of two 2-dim atoms (sample: order triangle + antisorted etc.)
xx = tuple(p[0] for p in F(2)[0]); yy = tuple(p[1] for p in F(2)[0])
def mt(a,b): return tuple(u & v for u,v in zip(a,b))
def jn(a,b): return tuple(u | v for u,v in zip(a,b))
O  = atom((mt(xx,yy), jn(xx,yy)), 2, 2)
Oa = atom((jn(xx,yy), mt(xx,yy)), 2, 2)
G  = atom((xx, yy), 2, 2)
shapes.append(("O-union-Oa", union(O, Oa)))
shapes.append(("O-union-G", union(O, G)))

bad = 0
for name, S in shapes:
    bt = betti(S, False); bs = betti(S, True)
    if bt != bs:
        bad += 1
        print(f"MISMATCH {name}: T-Betti {bt} vs Sing-Betti {bs}",
              flush=True)
print(f"cube^2 sweep: {len(shapes)} shapes, mismatches {bad}",
      flush=True)

# ---- cube^3 frontier atoms ----
_, D3 = F(3)
u3 = tuple(p[0] for p in F(3)[0]); v3 = tuple(p[1] for p in F(3)[0])
w3 = tuple(p[2] for p in F(3)[0])
def mt3(*xs):
    out = xs[0]
    for x in xs[1:]: out = tuple(a & b for a, b in zip(out, x))
    return out
def jn3(*xs):
    out = xs[0]
    for x in xs[1:]: out = tuple(a | b for a, b in zip(out, x))
    return out
T5 = (mt3(u3,v3,w3), mt3(u3,v3), mt3(u3, jn3(v3,w3)))
frontier = [("fivechain", T5)]
# sample: all z = triples of depth-2 polynomials with 4-chain image
import random
cands = []
for z in itertools.product([mt3(u3,v3,w3), mt3(u3,v3), mt3(u3,w3),
                            mt3(v3,w3), u3, v3, w3,
                            jn3(u3,v3), jn3(u3,w3), jn3(v3,w3),
                            mt3(u3,jn3(v3,w3)), mt3(v3,jn3(u3,w3)),
                            jn3(u3,mt3(v3,w3))], repeat=3):
    img = sorted(set(zip(*z)))
    # image poset chain length: longest chain in the image of
    # phi = z as map 2^3 -> 2^3 (use pointwise tuples)
    pts = list(set(zip(z[0], z[1], z[2])))
    def leq(a, b): return all(x <= y for x, y in zip(a, b))
    # longest chain by DP
    order = sorted(pts, key=lambda p: sum(p))
    best = {}
    mx = 1
    for i, p in enumerate(order):
        best[p] = 1 + max([best[q] for q in order[:i]
                           if q != p and leq(q, p)] or [0])
        mx = max(mx, best[p])
    if mx >= 4: cands.append(z)
random.seed(1); random.shuffle(cands)
frontier += [(f"4chain-{i}", z) for i, z in enumerate(cands[:12])]
bad3 = 0
for name, z in frontier:
    S = atom(z, 3, 3)
    bt = betti(S, False); bs = betti(S, True)
    tag = "MISMATCH" if bt != bs else "ok"
    if bt != bs: bad3 += 1
    print(f"cube^3 {name}: T {bt} vs Sing {bs} [{tag}]", flush=True)
print(f"cube^3 frontier: {len(frontier)} shapes, mismatches {bad3}",
      flush=True)
