"""O27 stage 14 (final form): Real Sing of the monotone dunce hat.
See TestComparison section 164.  Optimized computation: cells of
Real_D Sing_D W at levels k <= 2 as T-move classes of pairs
(q, sorted class s, decreasing tuple c), q <= 4, with the counit
value map.  RESULT: cells = values (2, 5, 24), zero splitting:
the T-moves already connect all presentations of each value, so
the counit is injective on cells with image the chain stratum --
the pattern identifications are generated by chains of T-moves
(the section-163 wall was illusory; single moves do not suffice
but move chains through hubs do)."""

import sys, itertools
sys.path.insert(0, 'scripts')
from dedekind_site import F, compose, cube_cells, all_maps, restrict, Quotient
from collections import defaultdict

QMAX = 4
W = Quotient(2, [(1, ((0,0), (0,1)), ((0,1), (0,0))),
                 (1, ((0,1), (0,1)), ((0,1), (1,1)))], QMAX)

def o_stat_t(j, m):
    pts, _ = F(m)
    if j <= 0: return tuple(1 for _ in pts)
    if j > m: return tuple(0 for _ in pts)
    return tuple(1 if sum(p) >= j else 0 for p in pts)

def sort_sub(q):
    return tuple(o_stat_t(j, q) for j in range(1, q + 1))

def act(cellcls, u, j, k):
    return W.cls(k, restrict(cellcls, u, 2, j, k))

sorted_cls = {}
for q in range(0, QMAX + 1):
    srt = sort_sub(q)
    sorted_cls[q] = [c for c in W.level(q) if act(c, srt, q, q) == c]
print("sorted:", [len(sorted_cls[q]) for q in range(QMAX+1)], flush=True)

def leq_t(a, b): return all(x <= y for x, y in zip(a, b))
def decreasing_tuples(q, k):
    _, Dk = F(k)
    if q == 0: return [()]
    return [c for c in itertools.product(Dk, repeat=q)
            if all(leq_t(c[i+1], c[i]) for i in range(q-1))]

def ordinal_maps(a, b):
    return [v for v in itertools.product(range(b+1), repeat=a+1)
            if all(v[i] <= v[i+1] for i in range(a))]

def Tmap(f, a, b):
    idx = []
    for i in range(1, b + 1):
        ks = [kk for kk in range(a + 1) if f[kk] >= i]
        idx.append(min(ks) if ks else a + 1)
    return tuple(o_stat_t(kk, a) for kk in idx)

for k in range(0, 3):
    DT = {q: decreasing_tuples(q, k) for q in range(QMAX+1)}
    pairs = [(q, s, c) for q in range(QMAX+1)
             for s in sorted_cls[q] for c in DT[q]]
    idx = {p: i for i, p in enumerate(pairs)}
    parent = list(range(len(pairs)))
    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]; i = parent[i]
        return i
    def union(i, j):
        ri, rj = find(i), find(j)
        if ri != rj: parent[ri] = rj
    for q in range(QMAX+1):
        for qp in range(QMAX+1):
            for h in ordinal_maps(qp, q):
                Th = Tmap(h, qp, q)
                sact = {}
                for s in sorted_cls[q]:
                    s2 = act(s, Th, q, qp)
                    if act(s2, sort_sub(qp), qp, qp) == s2:
                        sact[s] = s2
                for cp in DT[qp]:
                    c = tuple(compose(comp, cp, qp, k) for comp in Th)
                    if q > 0 and not all(
                        leq_t(c[i+1], c[i]) for i in range(q-1)):
                        continue
                    for s, s2 in sact.items():
                        key2 = (qp, s2, cp)
                        if key2 in idx:
                            union(idx[(q, s, c)], idx[key2])
    classes = defaultdict(list)
    for p in pairs: classes[find(idx[p])].append(p)
    vals = {}
    for root, ps in classes.items():
        q, s, c = ps[0]
        u = c if q > 0 else tuple()
        vals[root] = W.cls(k, restrict(s, u, 2, q, k))
    byval = defaultdict(list)
    for root, v in vals.items(): byval[v].append(root)
    split = {v: rs for v, rs in byval.items() if len(rs) > 1}
    print(f"level {k}: RealSingW cells = {len(classes)}, values = "
          f"{len(byval)}, split values = {len(split)}", flush=True)
