"""Dedekind-site probe engine (O22).

Free bounded distributive lattice F(k) = monotone functions
{0,1}^k -> {0,1} (Dedekind numbers 2, 3, 6, 20, 168, ...).
Cells of cube^n at level k = n-tuples over F(k); composition =
pointwise substitution.  Quotient objects W = cube^n / (list of
cell identifications), computed levelwise as the presheaf
congruence generated by the identifications (closure under
precomposition with all site maps).

Probes: strict endomorphisms of W, one-step strict homotopies
(level-(dim+1) cells with descent), and the reachability census
"is [id] connected to a constant class?" -- the stage-zero
signature of strict contractibility.

First checks: the circle S^1 = cube^1/(v0 ~ v1) must NOT have
id ~ const; the pinched square (one edge collapsed) SHOULD be
strictly contractible (connection cone).
"""
import itertools
from collections import deque

def monotone_fns(k):
    pts = list(itertools.product((0,1), repeat=k))
    fns = []
    for bits in itertools.product((0,1), repeat=len(pts)):
        f = dict(zip(pts, bits))
        if all(f[p] <= f[q] for p in pts for q in pts
               if all(a <= b for a, b in zip(p, q))):
            fns.append(tuple(bits))
    return pts, fns

CACHE = {}
def F(k):
    if k not in CACHE: CACHE[k] = monotone_fns(k)
    return CACHE[k]

def compose(phi, a, k_src, k_tgt):
    """phi in F(k_src) (function of k_src vars), a = tuple of
    k_src elements of F(k_tgt): substitution, result in F(k_tgt)."""
    pts_t, _ = F(k_tgt); pts_s, _ = F(k_src)
    idx_s = {p: i for i, p in enumerate(pts_s)}
    out = []
    for j, p in enumerate(pts_t):
        vals = tuple(a[i][j] for i in range(k_src))
        out.append(phi[idx_s[vals]])
    return tuple(out)

def cube_cells(n, k):
    """cells of cube^n at level k = n-tuples over F(k)"""
    _, fk = F(k)
    return list(itertools.product(fk, repeat=n))

def all_maps(j, k):
    """site maps [j] <- [k]?? convention: a map u: [k] -> [j]
    (for restriction along u of a level-j cell to level k) is a
    j-tuple over F(k)."""
    _, fk = F(k)
    return list(itertools.product(fk, repeat=j))

def restrict(cell, u, n, j, k):
    """cell = n-tuple over F(j); u = j-tuple over F(k):
    result = n-tuple over F(k): componentwise substitution."""
    return tuple(compose(c, u, j, k) for c in cell)

class Quotient:
    """W = cube^n / (identifications), levels 0..K"""
    def __init__(s, n, idents, K):
        s.n, s.K = n, K
        # idents: list of (level j, cellA, cellB)
        # congruence: generated by (A.u ~ B.u) for all u:[k]->[j]
        s.classes = {}
        for k in range(K + 1):
            cells = cube_cells(n, k)
            parent = {c: c for c in cells}
            def find(c):
                while parent[c] != c:
                    parent[c] = parent[parent[c]]; c = parent[c]
                return c
            def union(a, b):
                ra, rb = find(a), find(b)
                if ra != rb: parent[ra] = rb
            for (j, A, B) in idents:
                for u in all_maps(j, k):
                    union(restrict(A, u, n, j, k),
                          restrict(B, u, n, j, k))
            s.classes[k] = {c: find(c) for c in cells}
    def cls(s, k, cell): return s.classes[k][cell]
    def level(s, k): return sorted(set(s.classes[k].values()))

def probe(name, n, idents, K=None):
    if K is None: K = n + 1
    W = Quotient(n, idents, K)
    # strict endos: level-n cells with descent: an endo of W is a
    # class [F] (F an n-tuple over F(n)) such that for every
    # identification-generated relation at every level <= n the
    # induced condition holds; equivalently: whenever two site
    # maps u1, u2: [k] -> [n] have equal classes as cells of W
    # (i.e. cls(u1-as-cell) == cls(u2)), then
    # cls(F.u1) == cls(F.u2).  (Maps from the colimit W.)
    n_ = n
    endos = []
    idcell = tuple(tuple(1 if p[i] else 0 for p in F(n_)[0])
                   for i in range(n_))
    for Fc in cube_cells(n_, n_):
        ok = True
        for k in range(0, n_ + 1):
            # pairs of maps [k]->[n] with equal W-classes
            for u1 in all_maps(n_, k):
                c1 = W.cls(k, u1)
                # only need generators: compare with the class rep
                pass
            # efficient: group maps by W-class of the tuple itself
            groups = {}
            for u in all_maps(n_, k):
                groups.setdefault(W.cls(k, u), []).append(u)
            for g in groups.values():
                if len(g) < 2: continue
                c0 = W.cls(k, restrict(Fc, g[0], n_, n_, k))
                if any(W.cls(k, restrict(Fc, u, n_, n_, k)) != c0
                       for u in g[1:]):
                    ok = False; break
            if not ok: break
        if ok: endos.append(Fc)
    # classes of endos in W([n])
    endo_cls = {}
    for Fc in endos:
        endo_cls.setdefault(W.cls(n_, Fc), Fc)
    # one-step homotopies: level n+1 cells H (of W, with descent
    # as maps W x cube^1 -> W): H is an (n+1)-level n-tuple; the
    # descent condition: for u1 ~ u2: [k]->[n] (equal W-classes),
    # (u1 x id) vs (u2 x id): H.(u1 x id_t) ~ H.(u2 x id_t).
    # slices at t=0/1 give the connected endo classes.
    m = n_ + 1
    adj = {c: set() for c in endo_cls}
    _, fm = F(m)
    # t = last variable; u x id: [k+1] -> [n+1]
    pts_m = F(m)[0]
    cnt_h = 0
    for H in cube_cells(n_, m):
        # descent check
        ok = True
        for k in range(0, n_ + 1):
            groups = {}
            for u in all_maps(n_, k):
                groups.setdefault(W.cls(k, u), []).append(u)
            for g in groups.values():
                if len(g) < 2: continue
                exts = []
                for u in g:
                    # u x id: (n+1)-tuple over F(k+1):
                    # components: u_i lifted (ignore t), plus t
                    _, fk1 = F(k + 1)
                    ptsk1 = F(k + 1)[0]; ptsk = F(k)[0]
                    idxk = {p: i for i, p in enumerate(ptsk)}
                    lift = []
                    for comp in u:
                        lc = tuple(comp[idxk[p[:-1]]] for p in ptsk1)
                        lift.append(lc)
                    tvar = tuple(p[-1] for p in ptsk1)
                    uxid = tuple(lift) + (tvar,)
                    exts.append(restrict(H, uxid, n_, m, k + 1))
                c0 = W.cls(k + 1, exts[0])
                if any(W.cls(k + 1, e) != c0 for e in exts[1:]):
                    ok = False; break
            if not ok: break
        if not ok: continue
        cnt_h += 1
        # slices
        ptsm = F(m)[0]; ptsn = F(n_)[0]
        def slice_at(eps):
            idxm = {p: i for i, p in enumerate(ptsm)}
            return tuple(tuple(comp[idxm[p + (eps,)]] for p in ptsn)
                         for comp in H)
        s0 = W.cls(n_, slice_at(0)); s1 = W.cls(n_, slice_at(1))
        if s0 in adj and s1 in adj:
            adj[s0].add(s1); adj[s1].add(s0)
    # connectivity: id vs constants
    idc = W.cls(n_, idcell)
    consts = set()
    for v in itertools.product((0,1), repeat=n_):
        cc = tuple(tuple(v[i] for _ in F(n_)[0]) for i in range(n_))
        consts.add(W.cls(n_, cc))
    seen = {idc}; dq = deque([idc])
    while dq:
        x = dq.popleft()
        for y in adj.get(x, ()):
            if y not in seen: seen.add(y); dq.append(y)
    contractible = bool(seen & consts)
    print(f"{name}: level sizes "
          f"{[len(W.level(k)) for k in range(W.K+1)]}, "
          f"endo classes = {len(endo_cls)}, homotopy cells = {cnt_h}, "
          f"[id] ~ const: {contractible}", flush=True)
    return contractible

# vertex cells of cube^1 at level 0: 1-tuples over F(0) = {0, 1}
v0 = ((0,),); v1 = ((1,),)
# S^1: glue the two vertices of cube^1
probe("S1 = cube^1/(v0~v1)", 1, [(0, v0, v1)], K=2)
# collapsed interval: cube^1 with v0 ~ v1 AND the identity cell
# glued to the constant? no -- pinched square: cube^2 with one
# edge collapsed to a point: edge x=0 (the cell (0, y) at level 1
# ... as level-1 cell of cube^2: (const0, id)) collapsed:
# identify (const0, id) with (const0, const0):
c0 = (0,0); c1 = (1,1); idf = (0,1)   # F(1) elements as tuples
e_x0   = ((0,0),(0,1))     # cell (0, y)
e_pt0  = ((0,0),(0,0))     # constant vertex (0,0) at level 1
probe("pinched square = cube^2/(edge x=0 ~ point)", 2,
      [(1, e_x0, e_pt0)], K=3)
