"""O27 stage 4: the spectral tower of the incomparable-pair merge.

C = cube^3 / (spectral congruence with vertex fibers {a,b} merged),
a = 5 = (1,0,1), b = 6 = (0,1,1).  The spectral congruence at level
k identifies monotone vertex-functions with equal fiber patterns.
Question: is it generated by its pairs at levels <= L?  Check
L = 0, 1, 2 against levels 2 and 3 by union-find over instances.
Cells at level k: monotone maps {0,1}^k -> {0,1}^3, encoded as
tuples of vertex values.
"""
import sys, itertools
sys.path.insert(0, 'scripts')
from dedekind_site import F
from collections import defaultdict

A, B = 5, 6
LBL = list(range(8)); LBL[B] = A

def monmaps(k, tgt_pts=8):
    """monotone maps {0,1}^k -> {0,1}^3 as value tuples"""
    pts = list(range(1 << k))
    res = []
    def le(x, y): return (x & y) == x
    # build as triples of monotone fns (= D(k)^3), then to value tuples
    _, D = F(k)
    def to_int(t):
        n = 0
        for i, bit in enumerate(t): n |= bit << i
        return n
    Dk = [to_int(f) for f in D]
    seen = set()
    for s in itertools.product(Dk, repeat=3):
        vals = tuple((((s[0] >> x) & 1) | (((s[1] >> x) & 1) << 1)
                      | (((s[2] >> x) & 1) << 2)) for x in pts)
        seen.add(vals)
    return sorted(seen)

def pattern(vals): return tuple(LBL[v] for v in vals)

CACHE = {}
def cells(k):
    if k not in CACHE: CACHE[k] = monmaps(k)
    return CACHE[k]

def spectral_pairs(j):
    """all unordered pairs of distinct level-j cells with equal
    pattern"""
    groups = defaultdict(list)
    for c in cells(j): groups[pattern(c)].append(c)
    prs = []
    for g in groups.values():
        for i in range(len(g)):
            for l in range(i + 1, len(g)):
                prs.append((g[i], g[l]))
    return prs

def instances(pair, j, k):
    """(tau o rho, tau' o rho) for monotone rho: {0,1}^k -> {0,1}^j"""
    tau, taup = pair
    # rho = monotone map, encode as value tuple over {0,1}^k into
    # {0,1}^j: iterate monotone maps k->j = monmaps-like with target j
    key = ('rho', k, j)
    if key not in CACHE:
        _, D = F(k)
        def to_int(t):
            n = 0
            for i, bit in enumerate(t): n |= bit << i
            return n
        Dk = [to_int(f) for f in D]
        rhos = set()
        for s in itertools.product(Dk, repeat=j):
            rhos.add(tuple((sum((((s[m] >> x) & 1) << m) for m in range(j)))
                           for x in range(1 << k)))
        CACHE[key] = sorted(rhos)
    out = []
    for rho in CACHE[key]:
        out.append((tuple(tau[y] for y in rho),
                    tuple(taup[y] for y in rho)))
    return out

def check_generation(L, k):
    univ = cells(k)
    idx = {c: i for i, c in enumerate(univ)}
    parent = list(range(len(univ)))
    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]; x = parent[x]
        return x
    def union(x, y):
        rx, ry = find(x), find(y)
        if rx != ry: parent[rx] = ry
    for j in range(0, L + 1):
        for pair in spectral_pairs(j):
            for (c1, c2) in instances(pair, j, k):
                union(idx[c1], idx[c2])
    gen_classes = len(set(find(i) for i in range(len(univ))))
    true_classes = len(set(pattern(c) for c in univ))
    print(f"  L = {L} at level {k}: generated classes = {gen_classes}, "
          f"true (spectral) = {true_classes}, "
          f"{'GENERATES' if gen_classes == true_classes else 'falls short'}",
          flush=True)
    return gen_classes == true_classes

for k in (1, 2, 3):
    print(f"level {k}: cells = {len(cells(k))}, "
          f"spectral classes = {len(set(pattern(c) for c in cells(k)))}",
          flush=True)
for k in (2, 3):
    for L in range(0, k):
        if check_generation(L, k): break

# ---- addendum: n = 2 transversal sweep + C not-a-retract check ----
def sweep_n2():
    pts = list(range(4))
    def le(x, y): return (x & y) == x
    def parts(seq):
        if not seq:
            yield []; return
        x, rest = seq[0], seq[1:]
        for p in parts(rest):
            for i in range(len(p)):
                yield p[:i] + [p[i] + [x]] + p[i+1:]
            yield p + [[x]]
    total = kern = fail = 0
    for part in parts(pts):
        total += 1
        blocks = [tuple(b) for b in part]
        nb = len(blocks)
        lem = [[i == j for j in range(nb)] for i in range(nb)]
        for i, Bi in enumerate(blocks):
            for j, Bj in enumerate(blocks):
                if i != j and any(le(a, b) for a in Bi for b in Bj):
                    lem[i][j] = True
        for m in range(nb):
            for i in range(nb):
                if lem[i][m]:
                    for j in range(nb):
                        if lem[m][j]: lem[i][j] = True
        anti = all(not (lem[i][j] and lem[j][i])
                   for i in range(nb) for j in range(nb) if i != j)
        if not anti: continue
        kern += 1
        chosen = {}
        order = sorted(range(nb),
                       key=lambda i: sum(lem[j][i] for j in range(nb)))
        def bt(pos):
            if pos == nb: return True
            i = order[pos]
            for y in blocks[i]:
                ok = True
                for j, yj in chosen.items():
                    if lem[j][i] and not le(yj, y): ok = False; break
                    if lem[i][j] and not le(y, yj): ok = False; break
                if ok:
                    chosen[i] = y
                    if bt(pos + 1): return True
                    del chosen[i]
            return False
        if not bt(0): fail += 1
    print(f"n=2 sweep: partitions {total}, kernels {kern}, "
          f"WITHOUT transversal: {fail}")

def c_fiber_poset():
    # P_C = {0,1}^3 with 5 ~ 6 merged: check it is NOT a lattice
    elems = [0, 1, 2, 3, 4, 7, 'AB']
    def le(x, y):
        def pts(e): return [5, 6] if e == 'AB' else [e]
        return any((a & b) == a for a in pts(x) for b in pts(y))
    # meet of 3 (=110) and AB?
    lower = [z for z in elems if le(z, 3) and le(z, 'AB')]
    maximal = [z for z in lower
               if not any(z != w and le(z, w) for w in lower)]
    print(f"P_C: common lower bounds of 110 and AB: {lower}, "
          f"maximal: {maximal} -> lattice: {len(maximal) == 1}")

sweep_n2()
c_fiber_poset()
