"""Are finitely generated sublattices of free bounded DLs
retracts?  A sublattice A = <a_1..a_r> <= D(k) is a retract iff
there exist c_1..c_k in A with t_j(c) = a_j for the defining
terms -- by freeness, equivalently: iff there is a lattice map
rho: D(k) -> A (arbitrary images of generators) restricting to
the identity on A.  Since a lattice map D(k) -> A is any choice
of c in A^k (freeness!), and it restricts to id_A iff it fixes
a generating set, the condition is: exists c in A^k with
  eval of a_j's canonical term at c  ==  a_j.
But careful: a_j may have MANY terms; fixing a_j as an element
means: the induced map sends a_j to a_j.  The induced map sends
f(u_1..u_k) |-> f(c_1..c_k); a_j = a_j(u) as an ELEMENT of D(k)
is a specific monotone function; its image is a_j(c_1,...,c_k)
(substitution).  So condition: a_j(c) = a_j for all j -- and
then EVERY element of A is fixed (A generated by the a_j's and
the map is a lattice hom).  Sweep small cases."""
import sys, itertools
sys.path.insert(0, 'scripts')
from dedekind_site import F, compose

def proj(k, i):
    pts, _ = F(k)
    return tuple(p[i] for p in pts)

def meet(a,b): return tuple(x & y for x, y in zip(a,b))
def join(a,b): return tuple(x | y for x, y in zip(a,b))

def sublattice(gens, k):
    pts, _ = F(k)
    bot = tuple(0 for _ in pts); top = tuple(1 for _ in pts)
    A = set([bot, top]) | set(gens)
    changed = True
    while changed:
        changed = False
        cur = list(A)
        for x in cur:
            for y in cur:
                for z in (meet(x,y), join(x,y)):
                    if z not in A:
                        A.add(z); changed = True
    return A

def substitute(f, cs, k):
    # f in D(k) as bit-tuple over F(k)[0]; cs = k elements of D(k):
    # f(c_1..c_k) via compose: f o (c_1,...,c_k): [k]->[k]
    return compose(f, tuple(cs), k, k)

def is_retract(gens, k):
    A = sublattice(gens, k)
    Alist = sorted(A)
    for cs in itertools.product(Alist, repeat=k):
        ok = True
        for a in gens:
            if substitute(a, cs, k) != a:
                ok = False; break
        if ok:
            return True, A, cs
    return False, A, None

# sweep: 2-generated sublattices of D(3) and D(4); 3-generated of D(3)
import random
random.seed(0)

for k, r, mode in ((3, 2, 'full'), (3, 3, 'full'), (4, 2, 'sample')):
    _, Fk = F(k)
    nonzero = [f for f in Fk]
    pairs_checked = 0; nonretract = 0; examples = []
    if mode == 'full':
        combos = itertools.combinations(Fk, r)
    else:
        allc = list(itertools.combinations(Fk, r))
        random.shuffle(allc)
        combos = allc[:4000]
    for gens in combos:
        pairs_checked += 1
        okr, A, cs = is_retract(list(gens), k)
        if not okr:
            nonretract += 1
            if len(examples) < 3:
                examples.append((gens, len(A)))
    print(f"D({k}), {r}-generated ({mode}): checked={pairs_checked} "
          f"non-retract={nonretract}", flush=True)
    for g, na in examples:
        print("   counterexample gens:", g, "|A| =", na, flush=True)
