"""O28 stage 5b: refined skeleton check for the extension (Step).

fresh pairs := K-pairs NOT in the congruence generated by
  (pairs with prescribed value, i.e. class meets Ch(X) or lower
   attachment -- here approximated by Ch(X)) and
  (H_x-orbit pairs, instance-closed).
Claims to verify on samples:
 (b') every fresh class's members generate PROPER atoms
      (trackable), and none is invertible;
 (c') chain cells of track atoms have prescribed values;
 (e') minimality: non-invertible self-stabilizers are detected
      and the retract atom identified (idempotent power).
"""
import sys, itertools
sys.path.insert(0, 'scripts')
from dedekind_site import F, compose, restrict, Quotient
from collections import defaultdict

def rest(cell, u, j, k):
    return tuple(compose(c, u, j, k) for c in cell)
def leq_t(a, b): return all(x <= y for x, y in zip(a, b))
def comparable(a, b): return leq_t(a, b) or leq_t(b, a)
K = 3

def is_perm(u, n):
    pts, _ = F(n)
    projs = [tuple(p[i] for p in pts) for i in range(n)]
    return sorted(u) == sorted(projs)

class UF:
    def __init__(s): s.p = {}
    def find(s, x):
        s.p.setdefault(x, x)
        while s.p[x] != x:
            s.p[x] = s.p[s.p[x]]; x = s.p[x]
        return x
    def union(s, a, b):
        ra, rb = s.find(a), s.find(b)
        if ra != rb: s.p[ra] = rb

def analyze(name, n, idents):
    X = Quotient(n, idents, K)
    _, Dn = F(n)
    pts, _ = F(n)
    gen = tuple(tuple(p[i] for p in pts) for i in range(n))
    self_stab = [u for u in itertools.product(Dn, repeat=n)
                 if X.classes[n][u] == X.classes[n][gen]]
    noninv = [u for u in self_stab if not is_perm(u, n)]
    H = [u for u in self_stab if is_perm(u, n)]
    if noninv:
        # minimality reduction: idempotent power of a witness
        e = noninv[0]
        while True:
            e2 = tuple(compose(c, e, n, n) for c in e)
            if e2 == e: break
            e = e2
        At = {rest(e, u, n, 2) for u in
              itertools.product(F(2)[1], repeat=n)}
        print(f"{name}: NON-MINIMAL (self-stab {len(noninv)} "
              f"non-inv); retract to atom of idempotent, "
              f"|atom level2| = {len(At)} < {len(Dn)**0 or ''}"
              f"{len(list(itertools.product(F(2)[1],repeat=n)))}",
              flush=True)
        return
    # chain stratum values (prescribed zone)
    def o_stat_t(j, m):
        p2, _ = F(m)
        if j <= 0: return tuple(1 for _ in p2)
        if j > m: return tuple(0 for _ in p2)
        return tuple(1 if sum(q) >= j else 0 for q in p2)
    def sort_sub(q): return tuple(o_stat_t(j,q) for j in range(1,q+1))
    ChX = {k: set() for k in range(K + 1)}
    for q in range(K + 1):
        for c in X.level(q):
            if X.cls(q, rest(c, sort_sub(q), q, q)) != c: continue
            for k in range(K + 1):
                _, Dk = F(k)
                subs = [()] if q == 0 else \
                    [u for u in itertools.product(Dk, repeat=q)
                     if all(comparable(a,b) for a,b in
                            itertools.combinations(u,2))]
                for u in subs:
                    ChX[k].add(X.cls(k, rest(c, u, q, k)))
    # congruence generated by prescribed pairs + H-pairs
    ufs = {m: UF() for m in range(K + 1)}
    for m in range(K + 1):
        _, Dm = F(m)
        cls_of = defaultdict(list)
        for t in itertools.product(Dm, repeat=n):
            cls_of[X.classes[m][t]].append(t)
        for xc, mem in cls_of.items():
            if xc in ChX[m]:            # prescribed: merge all
                for t in mem[1:]:
                    ufs[m].union(mem[0], t)
        # H-pairs, instance closed: t ~ (h-permuted t)
        for t in itertools.product(Dm, repeat=n):
            for h in H:
                th = tuple(compose(hc, t, n, m) for hc in h)
                ufs[m].union(t, th)
    ok = True
    nfresh = 0
    for m in range(K + 1):
        _, Dm = F(m)
        cls_of = defaultdict(list)
        for t in itertools.product(Dm, repeat=n):
            cls_of[X.classes[m][t]].append(t)
        for xc, mem in cls_of.items():
            if xc in ChX[m]: continue
            reps = defaultdict(list)
            for t in mem: reps[ufs[m].find(t)].append(t)
            if len(reps) < 2: continue       # no fresh relations
            nfresh += 1
            for t in mem:
                if m == n and is_perm(t, n):
                    ok = False
                    print(f"  (b') FAIL: invertible member in "
                          f"fresh class, level {m}", flush=True)
                At = {rest(t, u, m, n)
                      for u in itertools.product(Dn, repeat=m)}
                if gen in At:
                    ok = False
                    print(f"  (b') FAIL: fresh member's atom "
                          f"contains generic, level {m}", flush=True)
                # (c') chain cells of the track atom prescribed
                for k in range(K + 1):
                    _, Dk = F(k)
                    subs = [()] if m == 0 else \
                        [u for u in itertools.product(Dk, repeat=m)
                         if all(comparable(a,b) for a,b in
                                itertools.combinations(u,2))]
                    for u in subs:
                        cell = rest(t, u, m, k)
                        if all(comparable(a,b) for a,b in
                               itertools.combinations(cell,2)):
                            if X.classes[k][cell] not in ChX[k]:
                                ok = False
                                print(f"  (c') FAIL level {m}->{k}",
                                      flush=True)
    print(f"{name}: |H| {len(H)}, fresh classes (lvl<=3) {nfresh}, "
          f"skeleton {'OK' if ok else 'FAIL'}", flush=True)

xx = tuple(p[0] for p in F(2)[0]); yy = tuple(p[1] for p in F(2)[0])
x1 = tuple(p[0] for p in F(1)[0])
c01 = tuple(0 for _ in F(1)[0]); c11 = tuple(1 for _ in F(1)[0])
A = (xx, yy, tuple(a & b for a, b in zip(xx, yy)))
B = (yy, xx, tuple(a & b for a, b in zip(xx, yy)))

analyze("W dunce hat", 2, [(1, (c01, x1), (x1, c01)),
                           (1, (x1, x1), (x1, c11))])
analyze("SP^2 (swap)", 2, [(2, (xx, yy), (yy, xx))])
analyze("cube^3/(A~B) fresh", 3, [(2, A, B)])
analyze("sortfold", 2, [(2, (xx, yy),
                         (tuple(a&b for a,b in zip(xx,yy)),
                          tuple(a|b for a,b in zip(xx,yy))))])
analyze("swap+fresh mix", 3, [(2, A, B),
                              (2, (xx, yy, tuple(a|b for a,b in
                                                 zip(xx,yy))),
                               (yy, xx, tuple(a|b for a,b in
                                              zip(xx,yy))))])
