"""O26: mono-cellular presentations of the first regular atoms.

(1) Q* = square/(left = diag = top) equals the pushout of
      square  <-|  U3 = (left u diag u top)  -->  S
    along the monomorphism U3 -> square, where S is the circle
    cube^1/(v0 ~ v1) and U3 -> S folds all three edges onto the
    loop: machine check that the congruence of Q* coincides with
    the congruence generated by (l ~ d, d ~ t, v00 ~ v01) at all
    levels <= 3.  With Cisinski's closure theorems (Ast. 308,
    3.4.9/3.4.19/3.4.20/3.4.21 + 3.4.10) this exhibits Q* as
    mono-cellular, hence W-regular for EVERY localizer W --
    in particular W_type-regular.
(2) The order triangle O = <(u&v, u|v)> (the subobject of
    ordered pairs, Spec of the four-chain) has 3 vertices,
    hence is not representable: the first cyclic atom beyond
    the graph machinery.
"""
import sys
sys.path.insert(0, 'scripts')
from dedekind_site import F, Quotient, cube_cells

def proj(k, i):
    pts, _ = F(k)
    return tuple(p[i] for p in pts)
def const(k, e):
    return tuple(e for _ in F(k)[0])

u1 = proj(1,0); c01 = const(1,0); c11 = const(1,1)
A_l = (c01, u1); A_d = (u1, u1); A_t = (u1, c11)
v00 = (const(0,0), const(0,0))
v01 = (const(0,0), const(0,1))

Q1 = Quotient(2, [(1, A_l, A_d), (1, A_l, A_t)], 3)
Q2 = Quotient(2, [(1, A_l, A_d), (1, A_d, A_t), (0, v00, v01)], 3)

def partition(W, k):
    m = {}
    for c in cube_cells(2, k):
        m.setdefault(W.cls(k, c), set()).add(c)
    return sorted(frozenset(v) for v in m.values())

ok = all(partition(Q1, k) == partition(Q2, k) for k in range(4))
print("(1) Q* congruence == pushout congruence (levels 0..3):", ok)

# (2) order triangle O: vertices = ordered pairs a <= b of bits
verts = [(a, b) for a in (0,1) for b in (0,1) if a <= b]
print("(2) O has", len(verts), "vertices; representables have "
      "2^n: O is not representable")
print("=> MONO-CELLULAR PRESENTATIONS VERIFIED" if ok else "=> FAIL")
