"""O27 stage 6: are the subatom posets of finite atoms finite?

For the assembly task (rem:remaining (b)): if a finite atom has
only finitely many distinct subatoms <c>, then every subobject is
a finite union of atoms and the mono-saturated assembly of
sources terminates.  Probe: count distinct subatoms of cube^1,
cube^2 (and the order triangle O) generated by cells of level
<= L, fingerprinting a subatom by its cell sets at levels <= 3.
Stabilization in L = evidence of finiteness (and the level-3
fingerprint is exact for subobjects of cube^2 if distinct
subatoms differ by level <= 3; we also report fingerprint level
sensitivity).
"""
import sys, itertools
sys.path.insert(0, 'scripts')
from dedekind_site import F

def to_int(t):
    n = 0
    for i, b in enumerate(t): n |= b << i
    return n

def ints(k):
    pts, D = F(k)
    return [to_int(f) for f in D]

D = {k: ints(k) for k in range(0, 4)}

def compose1(p, rho, l, k):
    """p in D(l) as int over 2^l pts; rho = l-tuple of D(k)-ints;
    result = p o rho in D(k)"""
    out = 0
    for x in range(1 << k):
        idx = 0
        for i in range(l):
            idx |= ((rho[i] >> x) & 1) << i
        if (p >> idx) & 1: out |= 1 << x
    return out

def atom_fingerprint(cell, l, ncomp, maxlev=3):
    """cell = ncomp-tuple over D(l); fingerprint = frozenset of
    instance tuples at levels 0..maxlev"""
    fp = []
    for k in range(0, maxlev + 1):
        cells_k = set()
        for rho in itertools.product(D[k], repeat=l):
            cells_k.add(tuple(compose1(c, rho, l, k) for c in cell))
        fp.append(frozenset(cells_k))
    return tuple(fp)

for ncomp, name in ((1, 'cube^1'), (2, 'cube^2')):
    seen = {}
    for l in range(0, 4):
        for cell in itertools.product(D[l], repeat=ncomp):
            fp = atom_fingerprint(cell, l, ncomp)
            if fp not in seen:
                seen[fp] = (l, cell)
        print(f"{name}: distinct subatoms from generators of "
              f"level <= {l}: {len(seen)}", flush=True)

# ---- rank-collapse: does Stab(c) meet the through-[n] maps? ----
# c in D(l)^n; through-maps sigma = rho o w, rho: [n]->[l] in
# D(n)^l, w: [l]->[n] in D(l)^n; need c o sigma = c.
def compose_tuple(cell, rho, l, k):
    return tuple(compose1(comp, rho, l, k) for comp in cell)

def rank_collapse(l, n):
    # precompute all through-[n] endomorphisms of [l]
    through = set()
    for rho in itertools.product(D[n], repeat=l):   # rho: [n]->[l]
        for w in itertools.product(D[l], repeat=n): # w: [l]->[n]
            sigma = tuple(compose1(r, w, n, l) for r in rho)
            through.add(sigma)
    through = sorted(through)
    print(f"(l,n)=({l},{n}): through-[{n}] endos of [{l}]: "
          f"{len(through)}", flush=True)
    bad = []
    for c in itertools.product(D[l], repeat=n):
        ok = False
        for sigma in through:
            if compose_tuple(c, sigma, l, l) == c:
                ok = True; break
        if not ok:
            bad.append(c)
    print(f"(l,n)=({l},{n}): cells WITHOUT rank-collapse: {len(bad)}"
          + (f"  e.g. {bad[0]}" if bad else ""), flush=True)
    return bad

rank_collapse(2, 1)
rank_collapse(3, 2)
