"""H_*(el(cube^n/D); F_2) by the vertex-join model (O18, section 77).

Chain of identifications (section 77):
  el(cube^n) is contractible and its K-fixed subcategory is the stratum of
  K, nonempty and contractible exactly when K fixes a VERTEX, so
  el(cube^n) is a model for E_F(D) with F = the family generated by the
  vertex stabilisers.  A second model for E_F(D) is the infinite join
  V^{*oo} of the vertex D-set V = {0,1}^n, and el of a quotient is the
  strict quotient of el, so

        el(cube^n / D)  ~  V^{*oo} / D .

D permutes only the V-coordinates of a join simplex and the join
coordinates are distinct, so the action is ADMISSIBLE (an element fixing a
simplex fixes it pointwise) and the orbit chain complex computes the
homology of the quotient:

        C_k = F_2[ V^{k+1} / D ],   d = sum_i (delete coordinate i).

Calibration (published values):
  K <= B_2  : H_1,H_2,H_3 = 0,0,1     (RP^oo * RP^oo)
  H8 <= B_3 : 1,1,2
  H24 <= B_3: 1,2,4
"""
import itertools, sys
from collections import deque

def build(n):
    ELEMS = [(p, s) for p in itertools.permutations(range(n))
             for s in itertools.product((0, 1), repeat=n)]
    idx = {e: i for i, e in enumerate(ELEMS)}
    NE = len(ELEMS); ID = idx[(tuple(range(n)), (0,)*n)]
    def mmr(e1, e2):
        (p1, s1), (p2, s2) = e1, e2
        return (tuple(p2[p1[i]] for i in range(n)),
                tuple(s1[i] ^ s2[p1[i]] for i in range(n)))
    MUL = [[idx[mmr(ELEMS[a], ELEMS[b])] for b in range(NE)] for a in range(NE)]
    INV = [next(b for b in range(NE) if MUL[a][b] == ID) for a in range(NE)]
    ACT = []
    for a in range(NE):
        p, s = ELEMS[a]
        ACT.append([sum(((((v >> p[i]) & 1) ^ s[i]) << i) for i in range(n))
                    for v in range(1 << n)])
    return ELEMS, idx, ID, NE, MUL, INV, ACT

def el_homology(D, ACT, n, top=4, verbose=False):
    """H_k for k <= top-1, from C_0..C_top."""
    NV = 1 << n
    Dl = sorted(D)
    acts = [ACT[a] for a in Dl]
    orbits = []      # per level: list of canonical codes
    index = []       # per level: dict code -> orbit id
    for k in range(top + 1):
        m = k + 1
        size = NV ** m
        seen = bytearray(size)
        reps = []; ind = {}
        for code in range(size):
            if seen[code]: continue
            # decode
            t = []; c = code
            for _ in range(m):
                t.append(c % NV); c //= NV
            oid = len(reps); reps.append(code)
            for A in acts:
                c2 = 0
                for j in range(m - 1, -1, -1):
                    c2 = c2 * NV + A[t[j]]
                if not seen[c2]:
                    seen[c2] = 1; ind[c2] = oid
                else:
                    ind[c2] = oid
        orbits.append(reps); index.append(ind)
        if verbose: print(f"    C_{k}: {len(reps)} orbits")
    def faces(code, m):
        t = []; c = code
        for _ in range(m):
            t.append(c % NV); c //= NV
        out = []
        for i in range(m):
            u = t[:i] + t[i+1:]
            c2 = 0
            for j in range(len(u) - 1, -1, -1):
                c2 = c2 * NV + u[j]
            out.append(c2)
        return out
    def rank(k):
        """rank of d_k : C_k -> C_{k-1}"""
        piv = {}; r = 0
        for code in orbits[k]:
            v = 0
            for f in faces(code, k + 1):
                v ^= 1 << index[k-1][f]
            while v:
                l = v.bit_length() - 1
                if l in piv: v ^= piv[l]
                else:
                    piv[l] = v; r += 1; break
        return r
    rk = {k: rank(k) for k in range(1, top + 1)}
    H = {}
    for k in range(1, top):
        H[k] = len(orbits[k]) - rk[k] - rk[k + 1]
    H[0] = len(orbits[0]) - rk[1]
    return H

if __name__ == "__main__":
    def cl(MUL, ID, gens):
        S = {ID}; dq = deque([ID])
        while dq:
            x = dq.popleft()
            for g in gens:
                y = MUL[x][g]
                if y not in S: S.add(y); dq.append(y)
        return frozenset(S)
    print("calibration:")
    E2, i2, ID2, NE2, MUL2, INV2, ACT2 = build(2)
    K = cl(MUL2, ID2, [i2[((1, 0), (0, 0))], i2[((0, 1), (1, 1))]])
    print("  K <= B_2   :", el_homology(K, ACT2, 2, top=5),
          "[expect H_1,H_2,H_3 = 0,0,1]")
    E3, i3, ID3, NE3, MUL3, INV3, ACT3 = build(3)
    H8 = cl(MUL3, ID3, [i3[((1, 0, 2), (0, 0, 0))], i3[((0, 1, 2), (0, 1, 1))]])
    print("  H8 <= B_3  :", el_homology(H8, ACT3, 3, top=4),
          "[expect 1,1,2]")
    H24 = cl(MUL3, ID3, [i3[((0, 1, 2), (1, 0, 0))], i3[((0, 1, 2), (0, 1, 0))],
                         i3[((0, 1, 2), (0, 0, 1))], i3[((1, 2, 0), (0, 0, 0))]])
    print("  H24 <= B_3 :", el_homology(H24, ACT3, 3, top=4),
          "[expect 1,2,4]")
    B3 = cl(MUL3, ID3, [i3[((1, 0, 2), (0, 0, 0))], i3[((1, 2, 0), (0, 0, 0))],
                        i3[((0, 1, 2), (1, 0, 0))]])
    print("  B_3        :", el_homology(B3, ACT3, 3, top=4),
          "[expect 1,1,2]")
