"""H~(E(T)/M; F2) for a library of fixed-point-free finite M-sets
(O20, statement (O1)).  Orbit Cech model: A_k = F2[T^{k+1}/M].

Key test cases:
 - the 'Quillen side' (some elementary abelian 2-subgroup acts
   without fixed points): covered by Theorem A;
 - the 'S3 side' (every elementary abelian 2-subgroup has a fixed
   point, but M does not): S3 on 3 points, S4 on 4 points, etc.
   -- the open case that decides whether (O1) is true as stated.
Also sanity: odd-order M must give F2-acyclic (transfer)."""
import itertools
from collections import deque

def close_perms(gens, T):
    idp = tuple(range(T))
    def comp(a, b): return tuple(a[b[i]] for i in range(T))
    S = {idp} | set(gens); dq = deque(S)
    while dq:
        x = dq.popleft()
        for y in list(S):
            for z in (comp(x, y), comp(y, x)):
                if z not in S: S.add(z); dq.append(z)
    return sorted(S)

def rank(cols):
    piv = {}; r = 0
    for v in cols:
        while v:
            l = v.bit_length() - 1
            if l in piv: v ^= piv[l]
            else: piv[l] = v; r += 1; break
    return r

def betti(T, M, top):
    """reduced F2 Betti of E(T)/M in degrees 1..top-1"""
    reps = []; ind = []
    for k in range(top + 1):
        m = k + 1; size = T ** m
        arr = [-1] * size; rp = []
        for code in range(size):
            if arr[code] >= 0: continue
            t = []; c = code
            for _ in range(m): t.append(c % T); c //= T
            oid = len(rp); rp.append(code)
            for g in M:
                c2 = 0
                for j in range(m - 1, -1, -1): c2 = c2 * T + g[t[j]]
                arr[c2] = oid
        reps.append(rp); ind.append(arr)
    def dmat(k):
        cols = []
        for code in reps[k]:
            m = k + 1
            t = []; c = code
            for _ in range(m): t.append(c % T); c //= T
            v = 0
            for i in range(m):
                u = t[:i] + t[i+1:]; c2 = 0
                for j in range(len(u) - 1, -1, -1): c2 = c2 * T + u[j]
                v ^= 1 << ind[k-1][c2]
            cols.append(v)
        return cols
    r = {k: rank(dmat(k)) for k in range(1, top + 1)}
    return [len(reps[k]) - r[k] - r[k+1] for k in range(1, top)], \
           [len(rp) for rp in reps]

def elem_ab_2_all_fixed(M, T):
    """every elementary abelian 2-subgroup has a common fixed pt?"""
    invs = [g for g in M if g != tuple(range(T)) and
            all(g[g[i]] == i for i in range(T))]
    # check all elem-ab 2-subgroups generated by <=3 commuting invs
    import itertools as it
    def comp(a, b): return tuple(a[b[i]] for i in range(T))
    for k in (1, 2, 3):
        for combo in it.combinations(invs, k):
            if any(comp(a, b) != comp(b, a)
                   for a in combo for b in combo): continue
            sub = close_perms(list(combo), T)
            if not any(all(g[t] == t for g in sub) for t in range(T)):
                return False
    return True

CASES = []
# S3 on 3 points
CASES.append(("S3 on 3", 3, close_perms([(1,0,2),(0,2,1)], 3)))
# Z3 on 3 (odd order sanity: must be acyclic)
CASES.append(("Z3 on 3 (sanity)", 3, close_perms([(1,2,0)], 3)))
# S4 on 4 points
CASES.append(("S4 on 4", 4, close_perms([(1,0,2,3),(1,2,3,0)], 4)))
# A4 on 4 points (V<=A4 is fixed-point-free elem-ab: Thm A side)
CASES.append(("A4 on 4", 4, close_perms([(1,2,0,3),(0,2,3,1)], 4)))
# D4 on 4 (vertices of square; diagonal reflections fix pts)
CASES.append(("D4 on 4", 4, close_perms([(1,2,3,0),(1,0,3,2)], 4)))
# S3 x S3 on 3+3 (every elt has fixed pt? transpositions etc.)
g1 = (1,0,2, 3,4,5); g2 = (0,2,1, 3,4,5)
h1 = (0,1,2, 4,3,5); h2 = (0,1,2, 3,5,4)
CASES.append(("S3xS3 on 3+3", 6, close_perms([g1,g2,h1,h2], 6)))
# S3 diagonal on 3+3 (same S3 acting on two copies)
d1 = (1,0,2, 4,3,5); d2 = (0,2,1, 3,5,4)
CASES.append(("S3 diag on 3+3", 6, close_perms([d1,d2], 6)))
# S5 on 5 points
CASES.append(("S5 on 5", 5,
              close_perms([(1,0,2,3,4),(1,2,3,4,0)], 5)))

for name, T, M in CASES:
    fpf = not any(all(g[t] == t for g in M) for t in range(T))
    idp = tuple(range(T))
    stab_gen = close_perms(
        [g for g in M if g != idp and any(g[t] == t for t in range(T))],
        T) == M
    ea_fixed = elem_ab_2_all_fixed(M, T)
    top = 7 if T <= 4 else 6
    b, dims = betti(T, M, top)
    print(f"{name}: |M|={len(M)} fpf={fpf} "
          f"<stab-elts>=M: {stab_gen} all-elem-ab-2-fixed: {ea_fixed}")
    print(f"   dims={dims}")
    print(f"   H~ deg1..{top-1} = {b}", flush=True)
