"""Isotropy-poset skeleton of el(cube^n/H) (O20).

For H <= B_n, computes the combinatorial data that determines the
collage decomposition of el(cube^n/H) uniformly across the reversal
sites (el-invariance lemma): the poset of fixed loci of subgroups
with fixed cells, their dimensions and patterns, the H-orbits of
loci, the stabilizers and residual actions, and the free part.

This is the input skeleton for the F2-cohomology assembly (Betti
numbers of el via Mayer-Vietoris over the poset), and for checking
the non-domination hypothesis dimension by dimension.

Validation: K (two 1-dimensional strata, residual Z/2 each, free
part BK) and A4-type (one orbit of four lines, stabilizer Z/3
acting trivially, free part B(A4)).
"""
import itertools as it, collections, sys

def analyze(n, gens, name):
    ELEMS = []
    for p in it.permutations(range(n)):
        for s in it.product((0, 1), repeat=n):
            ELEMS.append((p, s))
    ID = (tuple(range(n)), (0,) * n)
    def mm(a, b):
        (p1, s1), (p2, s2) = a, b
        return (tuple(p2[p1[i]] for i in range(n)),
                tuple(s1[i] ^ s2[p1[i]] for i in range(n)))
    def inv(e):
        p, s = e
        q = [0] * n; t = [0] * n
        for i in range(n): q[p[i]] = i
        for i in range(n): t[i] = s[q[i]]
        return (tuple(q), tuple(t))
    def close(g):
        S = {ID} | set(g)
        dq = collections.deque(S)
        while dq:
            x = dq.popleft()
            for y in list(S):
                for z in (mm(x, y), mm(y, x)):
                    if z not in S:
                        S.add(z); dq.append(z)
        return S
    H = sorted(close(gens))

    def locus(S):
        """common fixed pattern of the set S of elements, or None;
        returns (classes, signs) with dimension = #classes"""
        parent = list(range(n)); par = [0] * n
        def find(i):
            r = i; acc = 0
            while parent[r] != r:
                acc ^= par[r]; r = parent[r]
            return r, acc
        for (p, s) in S:
            for i in range(n):
                (ri, pi), (rj, pj) = find(i), find(p[i])
                if ri == rj:
                    if (pi ^ pj) != (s[i] & 1):
                        return None
                else:
                    parent[ri] = rj; par[ri] = pi ^ pj ^ (s[i] & 1)
        cls = {}
        for i in range(n):
            r, pp = find(i)
            cls.setdefault(r, []).append((i, pp))
        out = []
        for v in cls.values():
            v = sorted(v)
            base = v[0][1]
            out.append(tuple(sorted((i, p ^ base) for (i, p) in v)))
        return tuple(sorted(out))

    # subgroups with fixed cells, up to H-conjugacy, and their loci
    # (enumerate subgroups generated by subsets of reflections+...:
    #  for the poset we need all pointwise stabilizers of loci =
    #  subgroups of the form Fix(locus); equivalently the closure
    #  system generated by the cyclic reflection subgroups.)
    refl = [h for h in H if h != ID and locus([h]) is not None]
    # pointwise stabilizer of a locus pattern:
    def fixer(pat):
        out = []
        for h in H:
            if h == ID:
                continue
            L = locus([h])
            if L is None:
                continue
            # h fixes the pat-locus iff pat refines h's fixed equations:
            # check directly: h fixes all cells of pat's locus iff
            # combining h with the pat-equations stays consistent AND
            # h's action restricted is trivial: test on the pattern:
            # locus(pat-elements + h) == pat
            out.append(h)
        return out

    # build the locus poset from intersections of reflection loci
    from itertools import combinations
    loci = {}
    frontier = []
    for r in refl:
        L = locus([r])
        loci.setdefault(L, set()).add(r)
        frontier.append((L, frozenset([r])))
    # close under joins (intersections of loci = locus of union)
    changed = True
    seen = {fs for _, fs in frontier}
    while changed:
        changed = False
        items = list(loci.items())
        for (L1, S1), (L2, S2) in combinations(items, 2):
            S = frozenset(S1 | S2)
            if S in seen:
                continue
            seen.add(S)
            L = locus(sorted(S))
            if L is not None:
                if L not in loci or not (S <= loci[L]):
                    loci.setdefault(L, set()).update(S)
                    changed = True
    # pointwise fixers and setwise stabilizers per locus
    def acts_trivially(h, pat):
        return locus(list(loci.get(pat, [])) + [h]) == pat if False else None
    print(f"{name}: |H|={len(H)} reflections={len(refl)} "
          f"distinct loci={len(loci)}")
    # H-orbits of loci: transport patterns directly
    def normalize(classes):
        out = []
        for cl in classes:
            cl = sorted(cl)
            base = cl[0][1]
            out.append(tuple(sorted((i, p ^ base) for (i, p) in cl)))
        return tuple(sorted(out))
    def act_pat(h, pat):
        """pattern of h . (locus of pat): slot j lies in the class of
        sigma^{-1}... a cell c with c_i = ~^{p_i} m_{cl(i)} maps to
        (h o c)_j = ~^{s_j + p_{sigma(j)}} m_{cl(sigma(j))}"""
        sg, ss = h
        out = []
        for cl in pat:
            newcl = []
            for (i, p) in cl:
                # slot j with sigma(j) = i, i.e., j = sigma^{-1}(i)
                j = sg.index(i)
                newcl.append((j, p ^ ss[j]))
            out.append(tuple(sorted(newcl)))
        return normalize(tuple(sorted(out)))
    orbits = []
    left = set(loci)
    while left:
        L = left.pop()
        orb = {act_pat(h, L) for h in H}
        left -= orb
        orbits.append(sorted(orb))
    results = []
    for orb in sorted(orbits, key=lambda o: -len(o[0])):
        L = orb[0]
        dim = len(L)
        classes = list(L)
        # setwise stabilizer and its residual signed-perm action on
        # the d classes: h in setstab maps class cl to class cl' with
        # a sign (as in act_pat, read off classwise)
        setstab = [h for h in H if act_pat(h, L) == L]
        residual = set()
        for h in setstab:
            sg, ss = h
            cmap = [None] * dim
            csgn = [0] * dim
            ok = True
            for ci, cl in enumerate(classes):
                imgs = set()
                for (i, p) in cl:
                    j = sg.index(i)
                    # slot j gets class of the image pattern
                    val = (p ^ ss[j])
                    # find which class of L contains slot j
                    for cj, cl2 in enumerate(classes):
                        d2 = dict(cl2)
                        if j in d2:
                            imgs.add((cj, val ^ d2[j]))
                            break
                if len(imgs) != 1:
                    ok = False
                    break
                cmap[ci], csgn[ci] = imgs.pop()
            if ok:
                residual.add((tuple(cmap), tuple(csgn)))
        # pointwise fixer = kernel of the residual map
        fixer_order = len(setstab) // max(1, len(residual))
        print(f"  locus-orbit: size={len(orb)} dim={dim} "
              f"|setwise|={len(setstab)} |residual|={len(residual)} "
              f"residual={sorted(residual) if dim<=2 else '...'}")
        results.append((len(orb), dim, len(setstab), sorted(residual)))
    # incidence poset of ALL loci (containment: L1 <= L2 iff the
    # L1-locus is a subpresheaf of the L2-locus, i.e., the pattern L1
    # refines-with-signs L2); plus connectivity/homotopy type of its
    # nerve (= el(Sigma) upstairs) and the H-action
    def leq_pat(L1, L2):
        # locus(L1) subset locus(L2): every cell of L1's locus lies in
        # L2's: equivalent to: the union system of both is L1
        merged = locus(list(loci[L1]) + list(loci[L2])) if False else None
        # direct: pattern L1 refines L2 iff each L2-class-with-signs is
        # a union-compatible coarsening... simpler: compare fixers:
        # locus(L1) subset locus(L2) iff every generator constraint of
        # L2 is implied by L1: check: combining L1's equations with
        # L2's changes nothing:
        return combine(L1, L2) == L1
    def combine(L1, L2):
        parent = list(range(n)); par = [0] * n
        def find(i):
            r = i; acc = 0
            while parent[r] != r:
                acc ^= par[r]; r = parent[r]
            return r, acc
        def add(cl):
            for (i, p) in cl[1:]:
                (ri, pi), (rj, pj) = find(cl[0][0]), find(i)
                if ri == rj:
                    if (pi ^ pj) != (cl[0][1] ^ p):
                        return False
                else:
                    parent[ri] = rj
                    par[ri] = pi ^ pj ^ (cl[0][1] ^ p)
            return True
        for cl in list(L1) + list(L2):
            if not add(list(cl)):
                return None
        cls = {}
        for i in range(n):
            r, pp = find(i)
            cls.setdefault(r, []).append((i, pp))
        out = []
        for v in cls.values():
            v = sorted(v)
            base = v[0][1]
            out.append(tuple(sorted((i, p ^ base) for (i, p) in v)))
        return tuple(sorted(out))
    allL = sorted(loci)
    edges = []
    for L1 in allL:
        for L2 in allL:
            if L1 != L2 and combine(L1, L2) == L1 and len(L1) < len(L2):
                edges.append((L1, L2))
    # Hasse reduction
    hasse = []
    for (a, b) in edges:
        if not any((a, c) in edges and (c, b) in edges
                   for c in allL if c != a and c != b):
            hasse.append((a, b))
    V = len(allL); E = len(hasse)
    comps = {L: L for L in allL}
    def froot(x):
        while comps[x] != x: x = comps[x]
        return x
    for (a, b) in hasse:
        ra, rb = froot(a), froot(b)
        if ra != rb: comps[ra] = rb
    ncomp = len({froot(L) for L in allL})
    b1 = E - V + ncomp
    print(f"  strata poset: |V|={V} hasse edges={E} components={ncomp} "
          f"first Betti of nerve={b1}  => el(Sigma) ~ "
          f"{'points' if E==0 else f'graph (wedge of {b1} circles per component-ish)'}")
    return results

if __name__ == "__main__":
    sw2 = ((1, 0), (0, 0)); nb2 = ((0, 1), (1, 1))
    analyze(2, [sw2, nb2], "K (n=2)")
    nb = ((0, 1, 2), (1, 1, 0)); n011 = ((0, 1, 2), (0, 1, 1))
    rot = ((1, 2, 0), (0, 0, 0)); sw = ((1, 0, 2), (0, 0, 0))
    analyze(3, [nb, n011, rot], "A4-type (n=3)")
    analyze(3, [nb, n011, rot, sw], "nested-24 (n=3)")
