"""Referee check: does a PROPER inclusion of atoms strictly decrease
the marked-lattice size |L|?

Atom <z> for z in D(k)^n: cells at level m = {z o u : u in D(m)^k}.
L(z) = bounded sublattice of D(k) generated by components of z.
For each cell y (level j <= JMAX) of <z>, compare:
  proper := atom(y) != atom(z) at some level <= LMAX
  |L(y)| vs |L(z)|
Violation: proper but |L(y)| == |L(z)|.
Also violation type 2 (lem:minpres): idempotent-power reduction:
find b, e non-invertible with b.e^N = b (so reduction vacuous) but
b.e not a permutation instance of b.
"""
import sys, itertools
sys.path.insert(0, '/Users/shibusawa/Dev/DIT/FormalizedMathematics/scripts')
from dedekind_site import F, compose

LMAX = 3   # compare atoms at levels 0..LMAX
JMAX = 3   # cells y at levels 0..JMAX

Dcache = {}
def D(m):
    if m not in Dcache:
        Dcache[m] = F(m)[1]
    return Dcache[m]

def sublattice_size(comps, k):
    # bounded sublattice of D(k) generated by comps (tuples of bits over 2^k pts)
    npts = 1 << k
    S = set(comps)
    S.add(tuple(0 for _ in range(npts)))
    S.add(tuple(1 for _ in range(npts)))
    changed = True
    while changed:
        changed = False
        cur = list(S)
        for a in cur:
            for b in cur:
                m = tuple(x & y for x, y in zip(a, b))
                j = tuple(x | y for x, y in zip(a, b))
                if m not in S: S.add(m); changed = True
                if j not in S: S.add(j); changed = True
    return len(S)

def atom_cells(z, k, n, lmax):
    # z: n-tuple of elements of D(k). cells at level m: z o u, u in D(m)^k
    out = {}
    for m in range(lmax + 1):
        Dm = D(m)
        cells = set()
        for u in itertools.product(Dm, repeat=k):
            cells.add(tuple(compose(c, u, k, m) for c in z))
        out[m] = cells
    return out

def run(k, n, gens):
    viol = 0; checked = 0
    for z in gens:
        Lz = sublattice_size(z, k)
        Az = atom_cells(z, k, n, LMAX)
        seen = set()
        for j in range(JMAX + 1):
            for y in Az[j]:
                if y in seen: continue
                seen.add(y)
                Ly = sublattice_size(y, j)
                if Ly > Lz:
                    print(f"  |L| INCREASED?! z={z} y={y}")
                if Ly < Lz: continue
                # equal size: is <y> proper (up to LMAX)?
                Ay = atom_cells(y, j, n, LMAX)
                proper = any(Ay[m] != Az[m] for m in range(LMAX + 1))
                checked += 1
                if proper:
                    viol += 1
                    print(f"  VIOLATION k={k} n={n}: z={z} (|L|={Lz}) "
                          f"proper subatom y={y} at level {j} with |L|={Ly}")
    return viol, checked

import random
random.seed(7)
total_v = 0
# (k, n) small exhaustive / sampled
for (k, n, sample) in [(1, 1, None), (1, 2, None), (2, 1, None),
                       (2, 2, None), (2, 3, 300), (3, 2, 300),
                       (3, 3, 200)]:
    Dk = D(k)
    allgens = list(itertools.product(Dk, repeat=n))
    if sample and len(allgens) > sample:
        gens = random.sample(allgens, sample)
    else:
        gens = allgens
    v, c = run(k, n, gens)
    total_v += v
    print(f"(k={k},n={n}) gens={len(gens)}: equal-|L| cells checked={c}, "
          f"violations={v}", flush=True)
print(f"TOTAL violations: {total_v}")
