"""Stratum data for the 10 mixed subgroups of B_3 with trivial realizable
characters (the candidate second-generation witnesses of theorem (S)).

For each such H: the reflection set R = {h != 1 with fixed cells}
(C1: every cycle has even sign-sum), the H-conjugation orbits on R,
the dimension of each fixed locus (= number of cycles of h), and the
pairwise intersection pattern (l_h1 and l_h2 share a fixed cell iff
<h1,h2> has a common fixed cell, decided by parity union-find, C2).
"""
import sys, itertools
sys.path.insert(0, 'scripts')

n = 3
ELEMS = []
for perm in itertools.permutations(range(n)):
    for signs in itertools.product((0,1), repeat=n):
        ELEMS.append((perm, signs))
ID = (tuple(range(n)), (0,)*n)

def mm(e1, e2):
    (p1, s1), (p2, s2) = e1, e2
    perm = tuple(p2[p1[i]] for i in range(n))
    signs = tuple(s1[i] ^ s2[p1[i]] for i in range(n))
    return (perm, signs)

def inv(e):
    p, s = e
    q = [0]*n; t = [0]*n
    for i in range(n): q[p[i]] = i
    for i in range(n): t[i] = s[q[i]]
    return (tuple(q), tuple(t))

def close(gens):
    S = {ID}; S |= set(gens)
    while True:
        new = {mm(a,b) for a in S for b in S} - S
        if not new: return frozenset(S)
        S |= new

def cycles(e):
    """cycles of the slot permutation with sign-sums (cell = POST action)"""
    p, s = e
    seen = [False]*n; out = []
    for i in range(n):
        if seen[i]: continue
        cyc = [i]; seen[i] = True; j = p[i]; sg = s[i]
        while j != i:
            seen[j] = True; cyc.append(j); sg ^= s[j]; j = p[j]
        out.append((tuple(cyc), sg & 1))
    return out

def has_fixed_cell(e):
    return e != ID and all(sg == 0 for _, sg in cycles(e))

def fixed_locus_dim(e):
    return len(cycles(e))

def common_fixed(hs):
    """C2: parity union-find on slots for the subgroup generated by hs"""
    H = close(hs)
    parent = list(range(n)); par = [0]*n
    def find(i):
        if parent[i] == i: return (i, 0)
        r, p0 = find(parent[i]); parent[i] = r; par[i] ^= p0
        return (r, par[i])
    for (p, s) in H:
        for i in range(n):
            (ri, pi), (rj, pj) = find(i), find(p[i])
            if ri == rj:
                if (pi ^ pj) != (s[i] & 1): return False
            else:
                parent[ri] = rj; par[ri] = pi ^ pj ^ (s[i] & 1)
                # re-root laziness ok
    return True

def realizable_chars_trivial(H):
    """C3 via middle level of L_3 (weight-3 points of {0,1}^6)"""
    pts = [p for p in range(64) if bin(p).count('1') == 3]
    def sub_pt(e, p):
        # substitution point map: sigma_e^* on literal points
        (pm, s) = e
        c = [(p >> i) & 1 for i in range(6)]
        d = [0]*6
        for i in range(n):
            vx, vnx = c[2*pm[i]], c[2*pm[i]+1]
            if s[i]: vx, vnx = vnx, vx
            d[2*i], d[2*i+1] = vx, vnx
        return sum(b << i for i, b in enumerate(d))
    def rho_pt(p):
        c = [(p >> i) & 1 for i in range(6)]
        d = []
        for i in range(n):
            d += [1 - c[2*i+1], 1 - c[2*i]]
        return sum(b << i for i, b in enumerate(d))
    Hl = sorted(H)
    # characters chi: H -> Z/2 via a small generating set (propagate, check)
    gens = []
    span = {ID}
    for e in Hl:
        if e in span: continue
        gens.append(e)
        span = set(close(gens))
        if len(span) == len(H): break
    chars = []
    for bits in itertools.product((0,1), repeat=len(gens)):
        chi = {ID: 0}
        for g, b in zip(gens, bits): chi[g] = b
        ok = True
        while ok and len(chi) < len(H):
            progressed = False
            for a in list(chi):
                for b in list(chi):
                    c = mm(a, b); v = chi[a] ^ chi[b]
                    if c in chi:
                        if chi[c] != v: ok = False; break
                    else:
                        chi[c] = v; progressed = True
                if not ok: break
            if not progressed: break
        if ok and len(chi) == len(H) and \
           all(chi[mm(a,b)] == chi[a]^chi[b] for a in Hl for b in Hl):
            chars.append(chi)
    realizable = []
    for chi in chars:
        # union-find with parity on middle-level points
        idx = {p: i for i, p in enumerate(pts)}
        parent = list(range(len(pts))); par = [0]*len(pts)
        def find(i):
            path = []
            while parent[i] != i:
                path.append(i); i = parent[i]
            p0 = 0
            for j in reversed(path):
                p0 ^= par[j]; parent[j] = i; par[j] = p0
            # recompute parities properly
            return i
        def findp(i):
            r = i; acc = 0
            while parent[r] != r:
                acc ^= par[r]; r = parent[r]
            return r, acc
        ok = True
        for h in Hl:
            if h == ID: continue
            for p in pts:
                q = sub_pt(h, p)
                if chi[h]: q = rho_pt(q)
                if bin(q).count('1') != 3: ok = False; break
                (ri, pi), (rj, pj) = findp(idx[p]), findp(idx[q])
                if ri == rj:
                    if (pi ^ pj) != chi[h]: ok = False; break
                else:
                    parent[ri] = rj; par[ri] = pi ^ pj ^ chi[h]
            if not ok: break
        if ok: realizable.append(chi)
    nontriv = [c for c in realizable if any(v for v in c.values())]
    return len(nontriv) == 0

# enumerate all subgroups (iterative extension)
subs = {frozenset([ID])}
frontier = {frozenset([ID])}
while frontier:
    newsubs = set()
    for H in frontier:
        for e in ELEMS:
            if e in H: continue
            H2 = close(set(H) | {e})
            if H2 not in subs: newsubs.add(H2)
    subs |= newsubs
    frontier = newsubs

targets = []
for H in sorted(subs, key=len):
    if len(H) == 1: continue
    refl = [h for h in H if has_fixed_cell(h)]
    if not refl: continue                      # free
    if common_fixed([h for h in H if h != ID]): continue  # fixed-layer
    if not realizable_chars_trivial(H): continue
    targets.append((H, refl))

print(f"mixed subgroups with trivial realizable characters: {len(targets)}")
for H, refl in targets:
    Hl = sorted(H)
    # conjugation orbits on the reflection set
    orbs = []
    left = set(refl)
    while left:
        h = left.pop()
        orb = {mm(mm(g, h), inv(g)) for g in H}
        orb &= set(refl) | {h}
        left -= orb
        orbs.append(sorted(orb))
    dims = sorted(fixed_locus_dim(h) for h in refl)
    # pairwise common fixed cells between distinct reflections
    inter = []
    for h1, h2 in itertools.combinations(refl, 2):
        inter.append(common_fixed([h1, h2]))
    # also: does any pair of DISTINCT loci (different h) intersect?
    print(f"|H|={len(H)}  #refl={len(refl)}  refl-orbits={len(orbs)} "
          f"(sizes {[len(o) for o in orbs]})  locus-dims={dims}  "
          f"pairwise-common-fixed: {sum(inter)}/{len(inter)}")
