"""Prerequisites of the remaining general theorem "reflection-generated
mixed => separation" (O18, section 76).

The E-resolution witness machine (section 40) needs a REFLECTION-FREE
NORMAL subgroup V <| H (then G = H/V acts freely on the E-part).  Here we
test, over every reflection-generated mixed subgroup of B_n (n <= 4):

  (a) does a nontrivial reflection-free normal V exist?
  (b) the maximal such V (the subgroup generated by all reflection-free
      normal subgroups -- is the set closed under products?);
  (c) if V exists, is H/V ever trivial (machine degenerates)?
  (d) the structure of the ones with NO nontrivial V.
"""
import itertools
from collections import deque, Counter

def build(n):
    ELEMS = [(p, s) for p in itertools.permutations(range(n))
             for s in itertools.product((0, 1), repeat=n)]
    idx = {e: i for i, e in enumerate(ELEMS)}
    NE = len(ELEMS); ID = idx[(tuple(range(n)), (0,)*n)]
    def mmr(e1, e2):
        (p1, s1), (p2, s2) = e1, e2
        return (tuple(p2[p1[i]] for i in range(n)),
                tuple(s1[i] ^ s2[p1[i]] for i in range(n)))
    MUL = [[idx[mmr(ELEMS[a], ELEMS[b])] for b in range(NE)] for a in range(NE)]
    INV = [next(b for b in range(NE) if MUL[a][b] == ID) for a in range(NE)]
    def cyc(e):
        p, s = e; seen = [False]*n; out = []
        for i in range(n):
            if seen[i]: continue
            sg = s[i]; j = p[i]; seen[i] = True
            while j != i:
                seen[j] = True; sg ^= s[j]; j = p[j]
            out.append(sg & 1)
        return out
    REFL = [a != ID and all(g == 0 for g in cyc(ELEMS[a])) for a in range(NE)]
    ACT = []
    for a in range(NE):
        p, s = ELEMS[a]
        ACT.append([sum(((((v >> p[i]) & 1) ^ s[i]) << i) for i in range(n))
                    for v in range(1 << n)])
    return ELEMS, idx, ID, NE, MUL, INV, REFL, ACT

for n in (2, 3, 4):
    ELEMS, idx, ID, NE, MUL, INV, REFL, ACT = build(n)
    def close(gens):
        S = {ID}; dq = deque([ID])
        while dq:
            x = dq.popleft()
            for g in gens:
                y = MUL[x][g]
                if y not in S: S.add(y); dq.append(y)
        return frozenset(S)
    subs = {frozenset([ID]): []}
    frontier = list(subs.items())
    while frontier:
        new = []
        for H, gens in frontier:
            for g in range(NE):
                if g in H: continue
                H2 = close(gens + [g])
                if H2 not in subs:
                    subs[H2] = gens + [g]; new.append((H2, gens + [g]))
        frontier = new
    subs = list(subs)
    tgt = []
    for H in subs:
        R = [a for a in H if REFL[a]]
        if not R: continue
        if any(all(ACT[a][v] == v for a in R) for v in range(1 << n)): continue
        if close(R) != H: continue                 # want reflection-generated
        tgt.append(H)
    noV = []; stats = Counter(); nojoin = [0]; nmax = Counter()
    for H in tgt:
        Vs = [M for M in subs
              if M <= H and len(M) > 1
              and not any(REFL[a] for a in M)
              and all(MUL[MUL[g][a]][INV[g]] in M for g in H for a in M)]
        if not Vs: noV.append(H)
        else:
            Vmax = max(Vs, key=len)
            stats[(len(H), len(Vmax), len(H)//len(Vmax))] += 1
            # NOT closed under join: the join of two reflection-free
            # normal subgroups may acquire a reflection, so V is genuine
            # CHOICE DATA (same phenomenon as the free-radical counter-
            # example of paper 14, section 118).
            J = close(sorted(set().union(*Vs)))
            if any(REFL[a] for a in J): nojoin[0] += 1
            maxi = [M for M in Vs
                    if not any(M < M2 for M2 in Vs)]
            nmax[len(maxi)] += 1
    print(f"n={n}: reflection-generated mixed subgroups: {len(tgt)}; "
          f"without a nontrivial reflection-free normal V: {len(noV)}")
    print(f"      join of reflection-free normals acquires a reflection "
          f"in {nojoin[0]} of them (V is choice data); number of MAXIMAL "
          f"choices: {dict(sorted(nmax.items()))}")
    if stats:
        print("      (|H|, |V_max|, |G|) multiset:",
              dict(sorted(stats.items())))
    for H in sorted(noV, key=len)[:8]:
        print(f"      NO V: |H|={len(H):3d} "
              f"elements={[ELEMS[a] for a in sorted(H)][:6]}"
              f"{'...' if len(H) > 6 else ''}")
