"""Inexpressibility of the join of two nuclei: search for a finite Heyting algebra H = Down(P), nuclei j1, j2 and
an element a such that the subalgebra generated by a under (meet, join, imp, bot, top, j1, j2) does not contain
(j1 v j2)(a).  Then no term chi(p) in the language of two nuclei defines the join nucleus."""
import itertools as it, sys
from nuclei_join_axiom import HA, nuclei, join_nucleus

def generated(H, j1, j2, a):
    S = {a, H.bot, H.top}; changed = True
    while changed:
        changed = False
        for x in list(S):
            for y in (j1[x], j2[x]):
                if y not in S: S.add(y); changed = True
            for z in list(S):
                for y in (H.meet(x, z), H.join(x, z), H.imp(x, z), H.imp(z, x)):
                    if y not in S: S.add(y); changed = True
    return S

def posets(n):
    """all partial orders on n points (as le matrices), generated from DAG edge subsets (not deduped by iso)."""
    pairs = [(i, j) for i in range(n) for j in range(n) if i < j]
    seen = set()
    for mask in range(1 << len(pairs)):
        le = [[i == j for j in range(n)] for i in range(n)]
        for k, (i, j) in enumerate(pairs):
            if mask >> k & 1: le[i][j] = True
        for k in range(n):
            for i in range(n):
                for j in range(n):
                    if le[i][k] and le[k][j]: le[i][j] = True
        key = tuple(map(tuple, le))
        if key in seen: continue
        seen.add(key); yield le

if __name__ == "__main__":
    nmax = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    found = 0
    for n in range(2, nmax + 1):
        for le in posets(n):
            H = HA(n, le)
            N = nuclei(H)
            for j1, j2 in it.combinations(N, 2):
                J = join_nucleus(H, j1, j2)
                for a in range(H.n):
                    if J[a] in (j1[a], j2[a]): continue
                    S = generated(H, j1, j2, a)
                    if J[a] not in S:
                        found += 1
                        if found <= 3:
                            print(f"FOUND: poset n={n} le={[[int(x) for x in r] for r in le]} |H|={H.n}")
                            print("  elements (down-sets):", [sorted(d) for d in H.el])
                            print("  j1 =", j1, " j2 =", j2, " join =", J, " a =", a, " join(a) =", J[a], " generated size", len(S))
                        break
                if found >= 3: break
            if found >= 3: break
        if found >= 3: break
    print("examples found:", found)
