"""Algebraic filtration test for lax logic with two nuclei.
H = Up(P) finite Heyting algebra, nuclei j1, j2 (all nuclei enumerated), D = sublattice generated by a random
finite subset G (always containing top).  Define on D the closure c_i(d) = meet{s in D ∩ Fix(j_i) : s >= d}.
Tests: (A) is c_i a nucleus on D (meet-preserving)?  (B) if D is closed under d -> s (Heyting implication of H)
for s in D ∩ (Fix(j1) ∪ Fix(j2)), is c_i a nucleus?  (C) does c_1 v c_2 (join in nuclei of D, = least common
fixed point in D) agree with j1 v j2 on elements of G whose join-values are in G?"""
import itertools as it, random, sys
from nuclei_join_axiom import HA, nuclei, join_nucleus

def sublattice(H, G):
    S = set(G) | {H.top}
    changed = True
    while changed:
        changed = False
        for a in list(S):
            for b in list(S):
                for c in (H.meet(a, b), H.join(a, b)):
                    if c not in S: S.add(c); changed = True
    return S

def closure_op(H, D, fix):
    F = [s for s in D if s in fix]
    def c(d):
        ups = [s for s in F if H.le(d, s)]
        m = min(ups, key=lambda s: len(H.el[s]))
        assert all(H.le(m, s) for s in ups)
        return m
    return {d: c(d) for d in D}

def is_nucleus_on(H, D, c):
    return all(c[H.meet(a, b)] == H.meet(c[a], c[b]) for a in D for b in D)

if __name__ == "__main__":
    random.seed(int(sys.argv[1]) if len(sys.argv) > 1 else 0)
    trials = int(sys.argv[2]) if len(sys.argv) > 2 else 20
    statA = [0, 0]; statB = [0, 0]; statC = [0, 0]
    for t in range(trials):
        n = random.choice([3, 4, 4, 5])
        le = [[i == j for j in range(n)] for i in range(n)]
        for _ in range(random.randint(0, n)):
            i, j = random.sample(range(n), 2); le[i][j] = True
        for k in range(n):
            for i in range(n):
                for j in range(n):
                    if le[i][k] and le[k][j]: le[i][j] = True
        if any(le[i][j] and le[j][i] and i != j for i in range(n) for j in range(n)): continue
        H = HA(n, le)
        if H.n > 14: continue
        N = nuclei(H)
        if len(N) > 40: N = random.sample(N, 40)
        for j1, j2 in it.product(N, repeat=2):
            J = join_nucleus(H, j1, j2)
            fix1 = {a for a in range(H.n) if j1[a] == a}; fix2 = {a for a in range(H.n) if j2[a] == a}
            for _ in range(3):
                G = set(random.sample(range(H.n), random.randint(1, min(4, H.n))))
                # Sigma-like: close G under j1, j2, J once (values of subformulas ◯ψ)
                G |= {j1[g] for g in list(G)} | {j2[g] for g in list(G)} | {J[g] for g in list(G)}
                D = sublattice(H, G)
                c1 = closure_op(H, D, fix1); c2 = closure_op(H, D, fix2)
                okA = is_nucleus_on(H, D, c1) and is_nucleus_on(H, D, c2)
                statA[0 if okA else 1] += 1
                # (B) close D under d -> s for s fixed
                D2 = set(D); changed = True
                while changed:
                    changed = False
                    for d in list(D2):
                        for s in list(D2):
                            if s in fix1 or s in fix2:
                                e = H.imp(d, s)
                                if e not in D2: D2.add(e); changed = True
                    D2 = sublattice(H, D2)
                c1b = closure_op(H, D2, fix1); c2b = closure_op(H, D2, fix2)
                okB = is_nucleus_on(H, D2, c1b) and is_nucleus_on(H, D2, c2b)
                statB[0 if okB else 1] += 1
                # (C) join agreement on G (for the D2 version)
                fixD = [s for s in D2 if s in fix1 and s in fix2]
                ok = True
                for g in G:
                    ups = [s for s in fixD if H.le(g, s)]
                    m = min(ups, key=lambda s: len(H.el[s]))
                    if m != J[g]: ok = False
                statC[0 if ok else 1] += 1
    print("A (D = generated sublattice): nucleus ok / fail =", statA)
    print("B (D closed under d->s, s fixed): nucleus ok / fail =", statB)
    print("C (join agreement on G, version B): ok / fail =", statC)
