"""T2, gap side: the isotropy witnesses that populate  W_test \\ W_type  on a
reversal cube site are indexed by mixed subgroups H <= B_n of the
hyperoctahedral group, via the criterion (paperW Thm B / thm:main-criterion):
  N := normal-closure of the reflections (coordinate reversals) of H;
  a test-not-type weak equivalence is attached to H  <=>  N is 'mixed'
  (contains a genuine reversal).  'Presents spaces at H' <=> no witness.
This realises, cell by cell, the interval [W_type,W_test] of Same(Presh(S)):
its gap is exactly the set of witness-bearing H.  We enumerate B_2 and B_3."""
from itertools import product, permutations
# B_n as signed permutations: (perm tuple, sign tuple in {+1,-1}^n).
def Bn(n):
    els=[]
    for p in permutations(range(n)):
        for s in product((1,-1),repeat=n):
            els.append((p,s))
    return els
def mul(a,b):           # (a after b): apply b then a
    (pa,sa),(pb,sb)=a,b
    p=tuple(pa[pb[i]] for i in range(len(pb)))
    s=tuple(sa[pb[i]]*sb[i] for i in range(len(pb)))
    return (p,s)
def inv(a):
    (p,s)=a; n=len(p); q=[0]*n; t=[0]*n
    for i in range(n): q[p[i]]=i
    for i in range(n): t[p[i]]=s[i]
    return (tuple(q),tuple(t))
def ident(n): return (tuple(range(n)),(1,)*n)
def is_reflection(a):   # a coordinate reversal: identity perm, exactly one sign flipped
    (p,s)=a
    return p==tuple(range(len(p))) and sum(1 for x in s if x==-1)==1
def has_reversal(G):    # 'mixed': some element flips a sign somewhere
    return any(any(x==-1 for x in s) for (p,s) in G)
def closure(gens,n):
    G={ident(n)}; frontier=list(gens)
    G.update(gens)
    changed=True
    while changed:
        changed=False
        cur=list(G)
        for a in cur:
            for b in cur:
                c=mul(a,b)
                if c not in G: G.add(c); changed=True
    return G
def normal_closure(H,S,n):   # normal closure of subset H inside group S
    N=set(H)
    changed=True
    while changed:
        changed=False
        for g in list(S):
            gi=inv(g)
            for h in list(N):
                c=mul(mul(g,h),gi)
                if c not in N: N.add(c); changed=True
    return closure(N,n)
def reflections_of(H):
    return [h for h in H if is_reflection(h)]
def analyse(n):
    Bfull=closure(Bn(n),n); Ball=list(Bfull)
    # sample structurally distinct H: generated by chosen elements
    import itertools
    seen=set(); rows=[]
    # enumerate subgroups generated by <=2 generators (enough to hit all types for n<=3)
    gens_pool=Ball
    subs=set()
    for k in (1,2):
        for combo in itertools.combinations(gens_pool,k):
            H=frozenset(closure(list(combo),n)); subs.add(H)
    for H in subs:
        Hl=list(H)
        mixedH=has_reversal(Hl)
        refl=reflections_of(Hl)
        N=normal_closure(refl,Bfull,n) if refl else {ident(n)}
        mixedN=has_reversal(N)
        witness = mixedH and mixedN     # criterion: mixed H with mixed reflection-closure
        rows.append((len(H),mixedH,len(refl),len(N),mixedN,witness))
    tot=len(subs)
    wit=sum(1 for r in rows if r[5])
    mixed=sum(1 for r in rows if r[1])
    print(f"B_{n}: |group|={len(Bfull)}, #subgroups(<=2 gen)={tot}")
    print(f"   mixed subgroups (contain a reversal): {mixed}")
    print(f"   witness-bearing H  (=> element of  W_test\\W_type): {wit}")
    print(f"   presents-spaces subgroups (no witness): {tot-wit}")
    # the pure-permutation subgroups: never witnesses (refl empty -> N trivial)
    pureP=sum(1 for r in rows if not r[1])
    print(f"   pure-permutation H (no reversal): {pureP}  -- all present spaces (interval trivial there)")
for n in (2,3):
    analyse(n); print()
