"""Random search for counterexamples to three-fold multiplicativity (the three-fold multiplicativity conjecture)
in transformation monoids: submonoids of T_k (maps on k points) generated by a few random
maps.  For idempotent two-sided ideals X, Y, Z != M we test whether
    X (x) Y (x) Z  ->  XY (x) Z
is a bijection (multitensor of tensor_multi.py).  Two-sided ideals of a finite monoid are
the down-sets of the J-order on principal ideals M a M; we enumerate them and keep the
idempotent ones (I I = I).  Prints every failure; summary at the end.
"""
import itertools as it, random, sys, time
from tensor_multi import multitensor, mult_map_bijective

def closure(gens, k):
    """submonoid of T_k generated by gens (tuples of length k); returns list of maps and Cayley table"""
    idm = tuple(range(k))
    elems = [idm]; seen = {idm}
    frontier = [idm]
    while frontier:
        nxt = []
        for a in frontier:
            for g in gens:
                c = tuple(g[a[i]] for i in range(k))  # g after a
                if c not in seen:
                    seen.add(c); elems.append(c); nxt.append(c)
        frontier = nxt
    idx = {e: i for i, e in enumerate(elems)}
    n = len(elems)
    T = [[idx[tuple(elems[b][elems[a][i]] for i in range(k))] for b in range(n)] for a in range(n)]
    # T[a][b] = index of (b after a) = a then b ; monoid multiplication a*b
    return elems, T

def two_sided_ideals(T, maxJ=16):
    """all two-sided ideals = unions of principal ideals M a M (down-sets of the J-order);
    returns None if there are more than maxJ distinct principal ideals."""
    n = len(T)
    princ = {}
    for a in range(n):
        I = frozenset(T[T[m][a]][m2] for m in range(n) for m2 in range(n))
        princ.setdefault(I, a)
    P = list(princ.keys())
    if len(P) > maxJ: return None
    ideals = set()
    for mask in range(1, 1 << len(P)):
        ideals.add(frozenset().union(*[P[i] for i in range(len(P)) if mask >> i & 1]))
    return sorted(ideals, key=len)

def product(T, A, B): return frozenset(T[a][b] for a in A for b in B)

def test_monoid(T, maxsize=60000, log=print):
    n = len(T); M = frozenset(range(n))
    allI = two_sided_ideals(T)
    if allI is None: return 0, 0, -1
    ideals = [I for I in allI if I and product(T, I, I) == I and I != M]
    fails = 0; tested = 0
    for X in ideals:
        for Y in ideals:
            for Z in ideals:
                if len(X) * len(Y) * len(Z) > maxsize: continue
                r = mult_map_bijective(T, [X, Y, Z], 0)
                tested += 1
                if r is None or not r[0]:
                    fails += 1
                    log(f"  FAIL |M|={n} |X|,|Y|,|Z|={len(X)},{len(Y)},{len(Z)} result={r}")
    return tested, fails, len(ideals)

if __name__ == "__main__":
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    trials = int(sys.argv[2]) if len(sys.argv) > 2 else 200
    random.seed(seed)
    t0 = time.time(); total = 0; totfail = 0; seen_tables = set()
    for trial in range(trials):
        k = random.choice([3, 4, 4, 5])
        ngen = random.choice([2, 2, 3])
        gens = [tuple(random.randrange(k) for _ in range(k)) for _ in range(ngen)]
        elems, T = closure(gens, k)
        if len(T) > 45 or len(T) < 4: continue
        key = tuple(map(tuple, T))
        if key in seen_tables: continue
        seen_tables.add(key)
        tested, fails, nid = test_monoid(T)
        total += tested; totfail += fails
        print(f"trial {trial}: k={k} |M|={len(T)} idempotent proper ideals={nid} triples tested={tested} fails={fails}", flush=True)
    print(f"DONE seed={seed} monoids={len(seen_tables)} triples={total} failures={totfail} time={time.time()-t0:.0f}s")
