"""Joins and meets of subvarieties in the sameness lattice, tested on mono-unary algebras.
Ambient variety: f^N = f^{N'} (locally finite).  Subvarieties V_{a,b}: f^a x = f^b x (a > b).
For a finite algebra A, the verbal congruence th_V(A) is the congruence generated by the
instances (f^a u, f^b u), u in A.  W_V = {h : A/th_V(A) -> B/th_V(B) bijective}.
Join of unars: V_{a,b} v V_{c,d} = V_{m + lcm(a-b, c-d), m}, m = max(b,d).
Test: W_{V v V'} == W_V  ∩  W_{V'} on all homs between algebras of size <= n.
"""
import itertools as it, sys
from math import gcd

def cg_unary(n, f, pairs):
    parent = list(range(n))
    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]; x = parent[x]
        return x
    def union(x, y):
        x, y = find(x), find(y)
        if x != y: parent[x] = y; return True
        return False
    todo = list(pairs)
    while todo:
        u, v = todo.pop()
        if union(u, v): todo.append((f[u], f[v]))
    return tuple(find(x) for x in range(n))

def fpow(f, k, x):
    for _ in range(k): x = f[x]
    return x

def verbal(n, f, a, b):
    return cg_unary(n, f, [(fpow(f, a, x), fpow(f, b, x)) for x in range(n)])

def induced_bijective(nA, fA, nB, fB, h, a, b):
    tA = verbal(nA, fA, a, b); tB = verbal(nB, fB, a, b)
    img = {}
    for x in range(nA):
        c = tA[x]; d = tB[h[x]]
        if c in img and img[c] != d: return False
        img[c] = d
    return len(set(img.values())) == len(set(tB)) and len(set(img.values())) == len(img)

def algebras(n, N, Np):
    for f in it.product(range(n), repeat=n):
        if all(fpow(f, N, x) == fpow(f, Np, x) for x in range(n)): yield f

def homs(nA, fA, nB, fB):
    for h in it.product(range(nB), repeat=nA):
        if all(h[fA[x]] == fB[h[x]] for x in range(nA)): yield h

def join(a, b, c, d):
    m = max(b, d); p = (a - b) * (c - d) // gcd(a - b, c - d)
    return m + p, m

if __name__ == "__main__":
    N, Np = int(sys.argv[1]), int(sys.argv[2])   # ambient f^N = f^Np
    nmax = int(sys.argv[3]) if len(sys.argv) > 3 else 4
    # candidate subvarieties: f^a = f^b with a > b, contained in ambient: need a-b | N-Np and b <= Np
    subs = [(a, b) for b in range(0, Np + 1) for a in range(b + 1, N + 1) if (N - Np) % (a - b) == 0]
    algs = {n: list(algebras(n, N, Np)) for n in range(1, nmax + 1)}
    print("subvarieties", subs, "algebras", {n: len(v) for n, v in algs.items()})
    for (a, b), (c, d) in it.combinations(subs, 2):
        J = join(a, b, c, d)
        cnt = fails = 0
        for nA in range(1, nmax + 1):
            for fA in algs[nA]:
                for nB in range(1, nmax + 1):
                    for fB in algs[nB]:
                        for h in homs(nA, fA, nB, fB):
                            inV = induced_bijective(nA, fA, nB, fB, h, a, b)
                            inVp = induced_bijective(nA, fA, nB, fB, h, c, d)
                            inJ = induced_bijective(nA, fA, nB, fB, h, *J)
                            cnt += 1
                            if (inV and inVp) != inJ:
                                fails += 1
                                if fails <= 3: print(f"  FAIL V={(a,b)} V'={(c,d)} join={J}: A={fA} B={fB} h={h} inV={inV} inV'={inVp} inJoin={inJ}")
        print(f"V={(a,b)} V'={(c,d)} join={J}: homs={cnt} failures={fails}", flush=True)
