"""Two counterexamples to  W_{V v V'} = W_V  ∩  W_{V'}  for subvarieties V, V' of a variety.
(1) Groups (congruence permutable, not distributive): V = A_8 = var(Z_8), V' = var(D_8).
    The modular group M_16 = <a,b | a^8 = b^2 = 1, b a b = a^5> lies in V v V' (it is a quotient of
    the 2-generated relatively free group of var(Z_8 x D_8)), is subdirectly irreducible, and
    V(M_16) = V'(M_16) = <a^4>; so the quotient M_16 -> M_16/<a^4> is in W_V  ∩  W_{V'} but not in W_{V v V'}.
(2) Bounded lattices with a constant c (congruence distributive, not permutable): V: c = 0, V': c = 1.
    B = 2 x 2 with c = (0,1), C = the chain {(0,0),(0,1),(1,1)}: the inclusion C -> B induces bijections
    on the V- and V'-reflections but is not an isomorphism.
"""
import itertools as it

# ---------- (1) groups ----------
def d8():
    # elements (r, s): r in Z_4 rotation, s in {0,1} flip; (r1,s1)*(r2,s2) = (r1 + (-1)^s1 r2, s1+s2)
    els = [(r, s) for r in range(4) for s in range(2)]
    def mul(x, y): return ((x[0] + (y[0] if x[1] == 0 else -y[0])) % 4, (x[1] + y[1]) % 2)
    return els, mul
def z8():
    return list(range(8)), lambda x, y: (x + y) % 8
def gmul(x, y):  # G = Z_8 x D_8
    return ((x[0] + y[0]) % 8, D8mul(x[1], y[1]))
D8els, D8mul = d8(); Z8els, Z8mul = z8()
G = [(z, d) for z in Z8els for d in D8els]
Ge = (0, (0, 0))
assert len(G) == 64

def m16():
    # elements a^i b^j, i in Z_8, j in Z_2;  b a = a^5 b  => (i1,j1)(i2,j2) = (i1 + 5^j1 i2, j1+j2)
    def mul(x, y): return ((x[0] + (y[0] if x[1] == 0 else 5 * y[0])) % 8, (x[1] + y[1]) % 2)
    return mul
M16mul = m16()

# relatively free group F(2) of var(G): subgroup of G^(G^2) generated by the coordinate projections
pairs = [(g, h) for g in G for h in G]           # 4096 coordinates
X = tuple(p[0] for p in pairs); Y = tuple(p[1] for p in pairs)
def tmul(u, v): return tuple(gmul(a, b) for a, b in zip(u, v))
# BFS over words, tracking the image in M16 under X->a=(1,0), Y->b=(0,1)
a, b = (1, 0), (0, 1)
E = tuple(Ge for _ in pairs)
seen = {E: (0, 0)}; frontier = [E]; consistent = True
while frontier:
    nxt = []
    for u in frontier:
        for gen, img in ((X, a), (Y, b)):
            w = tmul(u, gen); m = M16mul(seen[u], img)
            if w in seen:
                if seen[w] != m: consistent = False
            else:
                seen[w] = m; nxt.append(w)
    frontier = nxt
print("|F(2)| of var(Z_8 x D_8) =", len(seen), "; X->a, Y->b well defined (M_16 is a quotient):", consistent,
      "; image size", len(set(seen.values())))
# verbal subgroups of M16: V = A_8 (commutators and 8th powers), V' = var(D_8) (4th powers, [x,y]^2, [x^2,y], [[x,y],z])
M = [(i, j) for i in range(8) for j in range(2)]
def inv(x):
    for y in M:
        if M16mul(x, y) == (0, 0): return y
def comm(x, y): return M16mul(M16mul(inv(x), inv(y)), M16mul(x, y))
def power(x, n):
    r = (0, 0)
    for _ in range(n): r = M16mul(r, x)
    return r
def normal_closure(S):
    N = {(0, 0)} | set(S); changed = True
    while changed:
        changed = False
        for x in list(N):
            for y in list(N):
                z = M16mul(x, y)
                if z not in N: N.add(z); changed = True
            for g in M:
                z = M16mul(M16mul(inv(g), x), g)
                if z not in N: N.add(z); changed = True
    return N
VA8 = normal_closure([comm(x, y) for x in M for y in M] + [power(x, 8) for x in M])
VD8 = normal_closure([power(x, 4) for x in M] + [power(comm(x, y), 2) for x in M for y in M]
                     + [comm(power(x, 2), y) for x in M for y in M] + [comm(comm(x, y), z) for x in M for y in M for z in M])
print("A_8-verbal subgroup of M_16:", sorted(VA8), " var(D_8)-verbal subgroup:", sorted(VD8))
# subdirect irreducibility: unique minimal normal subgroup
normals = set()
for x in M:
    normals.add(frozenset(normal_closure([x])))
minimal = [N for N in normals if len(N) > 1 and not any(len(K) > 1 and K < N for K in normals)]
print("minimal normal subgroups of M_16:", [sorted(N) for N in minimal])

# ---------- (2) bounded lattices with a constant ----------
def cg_lat(n, meet, join, pairs):
    parent = list(range(n))
    def find(x):
        while parent[x] != x: parent[x] = parent[parent[x]]; x = parent[x]
        return x
    todo = list(pairs)
    while todo:
        u, v = todo.pop(); ru, rv = find(u), find(v)
        if ru == rv: continue
        parent[ru] = rv
        for c in range(n): todo += [(meet[u][c], meet[v][c]), (join[u][c], join[v][c])]
    return tuple(find(x) for x in range(n))
B = [(0, 0), (0, 1), (1, 0), (1, 1)]
bm = [[B.index((min(x[0], y[0]), min(x[1], y[1]))) for y in B] for x in B]
bj = [[B.index((max(x[0], y[0]), max(x[1], y[1]))) for y in B] for x in B]
c = B.index((0, 1)); bot = B.index((0, 0)); top = B.index((1, 1))
thV_B = cg_lat(4, bm, bj, [(c, bot)]); thVp_B = cg_lat(4, bm, bj, [(c, top)])
C = [(0, 0), (0, 1), (1, 1)]
cm = [[C.index((min(x[0], y[0]), min(x[1], y[1]))) for y in C] for x in C]
cj = [[C.index((max(x[0], y[0]), max(x[1], y[1]))) for y in C] for x in C]
thV_C = cg_lat(3, cm, cj, [(1, 0)]); thVp_C = cg_lat(3, cm, cj, [(1, 2)])
incl = [B.index(x) for x in C]
def bij(thA, thB, h):
    img = {}
    for x in range(len(thA)):
        if thA[x] in img and img[thA[x]] != thB[h[x]]: return False
        img[thA[x]] = thB[h[x]]
    return len(set(img.values())) == len(img) == len(set(thB))
print("lattice example: theta_V(B) =", thV_B, "theta_V'(B) =", thVp_B, "theta_V(C) =", thV_C, "theta_V'(C) =", thVp_C)
print("inclusion C -> B bijective on V-reflections:", bij(thV_C, thV_B, incl), "; on V'-reflections:", bij(thVp_C, thVp_B, incl), "; isomorphism:", False)
